/**
 * W4.3 cross-language redaction parity tests (VAL-W4-020).
 *
 * Loads the committed parity corpus at
 * ``tests/conformance/redaction/parity_fixtures.json`` (generated by
 * ``tests/conformance/redaction/generate_parity_fixtures.py`` from the
 * Python W3.3 engine) and asserts that the TypeScript W4.3 engine
 * produces byte-identical canonical bytes for each fixture.
 *
 * Per spec G.3 and CLAUDE.md keystone invariant #7, the SDK redaction
 * MUST be deterministic for the same ``(policy_version, salt_ref,
 * input)`` triple, and the Python and TypeScript implementations MUST
 * agree byte-for-byte (after JCS canonicalization). This test is the
 * structural enforcement of that invariant.
 *
 * The corpus excludes binary attachments (Py routes bytes through
 * ``_to_string`` whereas TS emits ``{_digest_sha256: hex}`` references
 * per VAL-W4-025); binary handling is verified separately in
 * ``w4_3_binary_attachments.test.ts``.
 *
 * ASCII-only per CLAUDE.md "ASCII-Safe Source".
 */

import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  _canonicalJsonStringify,
  loadRedactionPolicy,
  RedactionEngine,
  type SaltProvider,
} from "../src/redaction.js";

interface ParityFixture {
  readonly name: string;
  readonly policy: string;
  readonly salt_ref: string;
  readonly input: Record<string, unknown>;
  readonly canonical_redacted_hex: string;
  readonly canonical_redacted_sha256: string;
}

interface ParityCorpus {
  readonly schema_version: string;
  readonly tenant_salt_b64: string;
  readonly policies: Record<string, Record<string, unknown>>;
  readonly fixtures: ReadonlyArray<ParityFixture>;
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const CORPUS_PATH = path.join(
  REPO_ROOT,
  "tests",
  "conformance",
  "redaction",
  "parity_fixtures.json",
);

function loadCorpus(): ParityCorpus {
  const raw = fs.readFileSync(CORPUS_PATH, "utf8");
  return JSON.parse(raw) as ParityCorpus;
}

const corpus = loadCorpus();
const tenantSalt = Buffer.from(corpus.tenant_salt_b64, "base64");

const saltProvider: SaltProvider = (saltRef) => {
  if (saltRef === "tenant_salt_v3") return new Uint8Array(tenantSalt);
  throw new Error(`unknown salt_ref: ${saltRef}`);
};

// -----------------------------------------------------------------------------
// VAL-W4-020: TS engine produces byte-identical output to Python.
// -----------------------------------------------------------------------------

describe("VAL-W4-020: TS redaction emits byte-identical canonical bytes vs Python", () => {
  it("corpus loaded successfully with the expected schema_version", () => {
    expect(corpus.schema_version).toBe("relay.redaction_parity.v1");
    expect(corpus.fixtures.length).toBeGreaterThan(0);
    expect(Object.keys(corpus.policies)).toContain("BASE_POLICY");
  });

  for (const fixture of corpus.fixtures) {
    it(`fixture '${fixture.name}': TS canonical bytes equal Python canonical bytes`, () => {
      const policyBody = corpus.policies[fixture.policy];
      expect(policyBody, `policy '${fixture.policy}' missing from corpus`).toBeDefined();
      const policy = loadRedactionPolicy(policyBody as Record<string, unknown>);
      const engine = new RedactionEngine({ policy, saltProvider });

      const redacted = engine.redact(fixture.input);
      const tsCanonicalBytes = new TextEncoder().encode(_canonicalJsonStringify(redacted));
      const tsHex = Buffer.from(tsCanonicalBytes).toString("hex");
      const tsSha256 = crypto
        .createHash("sha256")
        .update(Buffer.from(tsCanonicalBytes))
        .digest("hex");

      // Primary assertion: byte-for-byte hex equality.
      expect(tsHex, `byte mismatch on fixture '${fixture.name}'`).toBe(
        fixture.canonical_redacted_hex,
      );
      // Cheap secondary: digest equality.
      expect(tsSha256).toBe(fixture.canonical_redacted_sha256);
    });
  }

  it("VAL-W4-020 evidence: every fixture in the corpus passed parity", () => {
    // Sanity: confirm the corpus exercises at least the curated coverage
    // matrix (regex matchers, redact/hash/drop actions, homoglyphs, deep
    // nesting, deterministic-key-ordering, no-match baseline).
    const names = corpus.fixtures.map((f) => f.name);
    expect(names).toContain("ascii-email-and-api-key-in-model-call");
    expect(names).toContain("secret-across-five-applies-to-fields");
    expect(names).toContain("cyrillic-A-homoglyph-api-key");
    expect(names).toContain("greek-A-homoglyph-api-key");
    expect(names).toContain("cyrillic-a-homoglyph-email-hash");
    expect(names).toContain("ssn-and-phone-in-tool-args");
    expect(names).toContain("no-match-clean-payload");
    expect(names).toContain("deterministic-keys-mixed-case");
    expect(names).toContain("nested-arrays-and-objects");
    expect(names).toContain("ascii-only-email-hash-determinism");
  });
});
