/**
 * W4.4 -- cross-language error envelope parity (VAL-W4-029).
 *
 * Loads the committed parity corpus at
 * ``tests/conformance/errors/parity_fixtures.json`` (generated by
 * ``tests/conformance/errors/generate_parity_fixtures.py`` from the
 * Python W3.4 hierarchy) and asserts:
 *
 *   1. Every Py-emitted envelope deserializes into the expected TS
 *      typed leaf (VAL-W4-028 cross-check).
 *   2. The deserialized exception's :meth:`toEnvelope` re-serializes to
 *      JCS-canonical bytes byte-equal to the Py canonical hex
 *      (VAL-W4-029).
 *
 * Per CLAUDE.md keystone invariant #10 (schema versioning) and the
 * spec B.4 closed envelope, the canonical bytes MUST agree across
 * languages for the same input. This test is the structural enforcement.
 *
 * ASCII-only per CLAUDE.md "ASCII-Safe Source".
 */

import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  RelayAuthError,
  RelayCanonicalStatusForbidden,
  RelayConfigError,
  RelayError,
  RelayEvidenceError,
  RelayEvidenceIncomplete,
  RelayGateError,
  RelayHandoffIncomplete,
  RelayIngestError,
  RelayLifecycleInvalid,
  RelayPolicyError,
  RelayRateLimitError,
  RelayReplayError,
  RelayReplayPrecondition,
  RelaySchemaError,
  RelaySidecarAuthError,
  RelaySidecarError,
  RelaySidecarNotReachable,
  RelaySidecarVersionMismatch,
  RelaySQLiteError,
  RelayUnknownError,
} from "../src/errors.js";

interface ParityFixture {
  readonly name: string;
  readonly wire_code: string;
  readonly expected_ts_class: string;
  readonly envelope: Record<string, unknown>;
  readonly canonical_hex: string;
  readonly canonical_sha256: string;
}

interface ParityCorpus {
  readonly schema_version: string;
  readonly fixtures: ReadonlyArray<ParityFixture>;
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const CORPUS_PATH = path.join(
  REPO_ROOT,
  "tests",
  "conformance",
  "errors",
  "parity_fixtures.json",
);

function loadCorpus(): ParityCorpus {
  const raw = fs.readFileSync(CORPUS_PATH, "utf8");
  return JSON.parse(raw) as ParityCorpus;
}

// JCS-compatible canonical JSON encoder. Mirrors the Python
// ``relay_schemas.envelopes.canonical_bytes`` byte-for-byte for the
// JSON value subset Relay envelopes use:
//   - sort object keys lexicographically (recursively)
//   - compact separators (no whitespace)
//   - arrays preserve order
//   - strings emitted via JSON.stringify (UTF-8 escapes match Py's
//     json.dumps with ensure_ascii=False on the value subset used by
//     this corpus -- ASCII-only strings)
function canonicalJsonStringify(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new Error("canonicalJsonStringify: non-finite number not allowed");
    }
    return JSON.stringify(value);
  }
  if (typeof value === "string") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return "[" + value.map(canonicalJsonStringify).join(",") + "]";
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).sort((a, b) =>
      a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0,
    );
    const parts: string[] = [];
    for (const [k, v] of entries) {
      parts.push(JSON.stringify(k) + ":" + canonicalJsonStringify(v));
    }
    return "{" + parts.join(",") + "}";
  }
  throw new Error(`canonicalJsonStringify: unsupported type ${typeof value}`);
}

const NAME_TO_CLASS: Record<string, typeof RelayError> = {
  RelayError,
  RelayIngestError,
  RelayCanonicalStatusForbidden,
  RelayHandoffIncomplete,
  RelayPolicyError,
  RelayAuthError,
  RelaySidecarAuthError,
  RelayRateLimitError,
  RelayGateError,
  RelayEvidenceError,
  RelayEvidenceIncomplete,
  RelayReplayError,
  RelayReplayPrecondition,
  RelaySchemaError,
  RelaySidecarError,
  RelaySidecarVersionMismatch,
  RelaySidecarNotReachable,
  RelaySQLiteError,
  RelayConfigError,
  RelayLifecycleInvalid,
  RelayUnknownError,
};

const corpus = loadCorpus();

describe("VAL-W4-029: TS error envelope round-trips byte-equal to Py", () => {
  it("corpus loaded successfully with the expected schema_version", () => {
    expect(corpus.schema_version).toBe("relay.error_envelope_parity.v1");
    expect(corpus.fixtures.length).toBeGreaterThanOrEqual(15);
  });

  for (const fixture of corpus.fixtures) {
    it(`fixture '${fixture.name}': TS deserialize + re-serialize is byte-equal to Py`, () => {
      // Step 1: deserialize the Py envelope into a typed TS exception.
      // The corpus envelope always has a 'code' field (validated by the
      // generator); cast through unknown to satisfy the ErrorEnvelopeWire
      // shape which requires 'code' to be present.
      const wireEnvelope = fixture.envelope as unknown as Parameters<
        typeof RelayError.fromEnvelope
      >[0];
      const err = RelayError.fromEnvelope(wireEnvelope);

      // Step 2: instanceof matches the expected TS class.
      const expectedClass = NAME_TO_CLASS[fixture.expected_ts_class];
      if (expectedClass === undefined) {
        throw new Error(`unknown expected_ts_class ${fixture.expected_ts_class}`);
      }
      expect(
        err instanceof expectedClass,
        `fixture '${fixture.name}' is ${err.constructor.name}, expected ${fixture.expected_ts_class}`,
      ).toBe(true);

      // Step 3: code is preserved verbatim.
      expect(err.code).toBe(fixture.wire_code);

      // Step 4: re-serialize to canonical bytes and compare hex + sha256.
      const envelope = err.toEnvelope();
      const canonical = canonicalJsonStringify(envelope);
      const canonicalBytes = Buffer.from(canonical, "utf8");
      const tsHex = canonicalBytes.toString("hex");
      const tsSha256 = crypto.createHash("sha256").update(canonicalBytes).digest("hex");

      expect(
        tsHex,
        `canonical-hex byte mismatch on fixture '${fixture.name}'`,
      ).toBe(fixture.canonical_hex);
      expect(tsSha256).toBe(fixture.canonical_sha256);
    });
  }

  it("the corpus exercises the full canonical code coverage matrix", () => {
    const codes = new Set(corpus.fixtures.map((f) => f.wire_code));
    // Spec B.4 closed-enum codes (VAL-W4-028).
    for (const required of [
      "RELAY-ING-001",
      "RELAY-ING-014",
      "RELAY-ING-021",
      "RELAY-ING-031",
      "RELAY-AUTH-001",
      "RELAY-AUTH-014",
      "RELAY-RATE-001",
      "RELAY-RATE-014",
      "RELAY-GATE-001",
      "RELAY-GATE-014",
      "RELAY-GATE-021",
      "RELAY-EVID-001",
      "RELAY-EVID-014",
      "RELAY-REPLAY-001",
      "RELAY-REPLAY-014",
    ]) {
      expect(codes, `corpus missing required code ${required}`).toContain(required);
    }
  });
});
