"""Generate the Python wasm-path golden for VAL-CWC-P1HOST-019.

This script drives each of the 3 native relay.* UDFs (relay.coverage,
relay.tool_arg, relay.schema_match) THROUGH the REAL Python wasm pipeline
(``packages/contracts/src/relay_contracts/pipeline.py`` ``evaluate_assertion``
under ``RELAY_CEL_ENGINE=wasm``) and records, per case:

  - the exact ``udf_outputs_jcs`` string the Python host emits (the
    typed-canonical ``{name: [{"t","v"}, ...]}`` per-UDF-name list in call
    order, JCS-canonicalized via the SAME ``jcs_canonicalize`` the digest
    consumes), and
  - the derived ``udfs_invoked`` list.

The TS pipeline mirror (``packages/contracts-typescript/src/pipeline.ts``)
MUST reconstruct BYTE-IDENTICAL ``udf_outputs_jcs`` from the SAME wasm
``udf_trace`` field. This is keystone invariant #16 (a P0): the
``udf_outputs_jcs`` bytes feed a cryptographic digest, so they MUST be
byte-identical across the Python and TS hosts.

The golden bytes are NOT hand-authored -- they are derived from the real
Python wasm path so the vitest cross-host parity test proves TRUE cross-host
byte-identity rather than agreement with a hand-written constant.

Run (from the relay repo root):

    RELAY_CEL_ENGINE=wasm uv run python \
      packages/contracts-typescript/test/fixtures/generate_udf_outputs_golden.py

This writes ``udf_outputs_jcs.golden.json`` next to this script. Re-running
against an unchanged wasm reproduces a byte-identical golden (deterministic).

ASCII-only per CLAUDE.md "ASCII-Safe Source".
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

from relay_contracts import RELAY_UDFS
from relay_contracts.dsl_parser import parse_contract
from relay_contracts.pipeline import evaluate_assertion

# The golden is meaningless unless the contracts factory is selecting the wasm
# engine (engine.py is the ONLY RELAY_CEL_ENGINE read site). Fail loud rather
# than silently record a celpy-path golden, which would defeat the cross-host
# byte-parity guarantee (the celpy and wasm paths emit the SAME typed-canonical
# bytes by design, but the golden's intent is to anchor the TS host against the
# wasm path specifically).
_WASM_SELECTED = os.environ.get("RELAY_CEL_ENGINE", "").strip() == "wasm"


def _doc(expression: str) -> dict[str, Any]:
    return {
        "schema_version": "relay.assertion.behavioral.v1",
        "assertion_id": "VAL-RT-WASM-GOLDEN",
        "kind": "behavioral",
        "expression": expression,
        "severity": "p0",
        "owner_email": "test@example.com",
        "lifecycle_state": "active",
    }


# Each case drives ONE logical scenario through the wasm pipeline. The label is
# the stable key the TS test reads; ``expression`` + ``bindings`` are the EXACT
# inputs the TS pipeline drives through the SAME wasm.
_CASES: list[dict[str, Any]] = [
    {
        "label": "coverage_single",
        "expression": 'relay.coverage(t, "alpha")',
        "bindings": {"t": {"steps": [{"name": "alpha"}, {"name": "beta"}]}},
    },
    {
        "label": "tool_arg_single",
        "expression": 'relay.tool_arg(call, "k") == "v"',
        "bindings": {"call": {"args": {"k": "v"}}},
    },
    {
        "label": "schema_match_single",
        "expression": "relay.schema_match(payload, sch)",
        "bindings": {"payload": "hello", "sch": {"type": "string"}},
    },
    {
        # Same UDF fired TWICE in call order: exercises the per-name call-order
        # list reconstruction (both hosts must agree on the order of the two
        # entries under the single "relay.coverage" key).
        "label": "coverage_repeated_call_order",
        "expression": (
            'relay.coverage(t, "alpha") && relay.coverage(t, "beta")'
        ),
        "bindings": {"t": {"steps": [{"name": "alpha"}, {"name": "beta"}]}},
    },
    {
        # No relay.* UDF executed -> udf_trace absent -> empty JCS object "{}".
        "label": "no_udf",
        "expression": "1 + 1 == 2",
        "bindings": {},
    },
]


def main() -> int:
    if not _WASM_SELECTED:
        sys.stderr.write(
            "ERROR: RELAY_CEL_ENGINE must be 'wasm' to generate the wasm-path "
            "golden. Re-run as:\n"
            "  RELAY_CEL_ENGINE=wasm uv run python "
            "packages/contracts-typescript/test/fixtures/"
            "generate_udf_outputs_golden.py\n"
        )
        return 2

    out: dict[str, Any] = {
        "comment": (
            "Python wasm-path golden for VAL-CWC-P1HOST-019. Generated by "
            "generate_udf_outputs_golden.py from the REAL Python wasm "
            "pipeline (RELAY_CEL_ENGINE=wasm). The TS pipeline mirror MUST "
            "reconstruct byte-identical udf_outputs_jcs from the same wasm "
            "udf_trace. Do NOT hand-edit."
        ),
        "engine": "wasm",
        "cases": [],
    }

    for case in _CASES:
        parsed = parse_contract(_doc(case["expression"]))
        envelope = evaluate_assertion(
            parsed, bindings=case["bindings"], extra_udfs=RELAY_UDFS
        )
        out["cases"].append(
            {
                "label": case["label"],
                "expression": case["expression"],
                "bindings": case["bindings"],
                # The exact JCS string the Python host emits. This is the
                # byte-for-byte parity target for the TS host.
                "udf_outputs_jcs": envelope["udf_outputs_jcs"],
                "udfs_invoked": envelope["udfs_invoked"],
                "outcome": envelope["outcome"],
            }
        )

    golden_path = Path(__file__).resolve().parent / "udf_outputs_jcs.golden.json"
    # Stable, deterministic serialization: 2-space indent, trailing newline,
    # ensure_ascii so the file itself is ASCII-only (the udf_outputs_jcs strings
    # are already ASCII for these cases; ensure_ascii keeps the file portable).
    golden_path.write_text(
        json.dumps(out, indent=2, ensure_ascii=True) + "\n", encoding="utf-8"
    )
    sys.stdout.write(f"wrote {golden_path} ({len(out['cases'])} cases)\n")
    for case in out["cases"]:
        sys.stdout.write(
            f"  {case['label']}: {case['udf_outputs_jcs']}\n"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
