# GENERATED FILE - DO NOT EDIT BY HAND.
#
# Source: packages/schemas/raw/openapi.yaml (W1.5 OpenAPI 3.1 source-of-truth).
# Regenerate: uv run python packages/schemas/scripts/codegen.py
# Drift check: uv run python scripts/check-codegen-drift.py
#
# Per VAL-W1-033 every class is a Pydantic v2 BaseModel subclass with
# model_config = ConfigDict(extra='forbid').

"""Field alias maps for VAL-W1-037 snake_case <-> camelCase boundary.

Canonical wire-format field names are snake_case (e.g. ``run_result_id``).
The Python side exposes snake_case attributes directly (Pydantic default).
The TS side uses camelCase property names with the alias mapping under
``packages/sdk-typescript/src/_generated/aliases.ts``.

The dictionaries below are the source-of-truth for the cross-language
round-trip test (VAL-W1-037): both languages MUST produce identical
serialized output when given the same snake_case wire payload.
"""

from __future__ import annotations

# Mapping per envelope: snake_case field name -> camelCase field name.
# Fields with no underscores (already camelCase-equivalent) are omitted.
FIELD_ALIASES_BY_ENVELOPE: dict[str, dict[str, str]] = {
    "Actor": {
        "created_at": "createdAt",
        "identity_hash": "identityHash",
        "revoked_at": "revokedAt",
    },
    "AssertionDefinition": {
        "applies_to": "appliesTo",
        "assertion_id": "assertionId",
        "created_at": "createdAt",
        "current_version": "currentVersion",
        "lifecycle_state": "lifecycleState",
        "owner_email": "ownerEmail",
        "project_id": "projectId",
        "schema_version": "schemaVersion",
        "updated_at": "updatedAt",
    },
    "ContractResult": {
        "assertion_id": "assertionId",
        "contract_id": "contractId",
        "contract_result_id": "contractResultId",
        "contract_version": "contractVersion",
        "evaluated_at": "evaluatedAt",
        "evaluation_engine_version": "evaluationEngineVersion",
        "raw_signature_hash": "rawSignatureHash",
        "repair_attempt": "repairAttempt",
        "run_id": "runId",
        "schema_version": "schemaVersion",
        "span_id": "spanId",
    },
    "EmbeddingSpan": {
        "cost_usd": "costUsd",
        "embedding_dim": "embeddingDim",
        "input_token_count": "inputTokenCount",
        "latency_ms": "latencyMs",
        "schema_version": "schemaVersion",
        "span_id": "spanId",
    },
    "ErrorEnvelope": {
        "blocked_surface": "blockedSurface",
        "http_status": "httpStatus",
        "request_id": "requestId",
        "retry_advice": "retryAdvice",
        "schema_version": "schemaVersion",
        "trace_id": "traceId",
    },
    "EventLogEntry": {
        "actor_id": "actorId",
        "actor_kind": "actorKind",
        "event_id": "eventId",
        "event_type": "eventType",
        "ingest_sequence": "ingestSequence",
        "manifest_commit_hash": "manifestCommitHash",
        "occurred_at": "occurredAt",
        "project_id": "projectId",
        "schema_version": "schemaVersion",
        "scope_id": "scopeId",
        "scope_type": "scopeType",
    },
    "EvidenceBundle": {
        "acef_core_version": "acefCoreVersion",
        "bundle_digest": "bundleDigest",
        "created_at": "createdAt",
        "evidence_bundle_id": "evidenceBundleId",
        "manifest_commit_hash": "manifestCommitHash",
        "object_ref": "objectRef",
        "org_id": "orgId",
        "project_id": "projectId",
        "redaction_policy_version": "redactionPolicyVersion",
        "relay_extension_version": "relayExtensionVersion",
        "schema_version": "schemaVersion",
        "scope_id": "scopeId",
        "scope_type": "scopeType",
        "signature_algorithm": "signatureAlgorithm",
        "signing_key_id": "signingKeyId",
        "supersedes_bundle_id": "supersedesBundleId",
        "verification_status": "verificationStatus",
    },
    "EvidenceBundleScopeState": {
        "created_at": "createdAt",
        "project_id": "projectId",
        "schema_version": "schemaVersion",
        "scope_id": "scopeId",
        "scope_kind": "scopeKind",
        "updated_at": "updatedAt",
    },
    "EvidenceClaim": {
        "claim_digest": "claimDigest",
        "claim_type": "claimType",
        "created_at": "createdAt",
        "evidence_bundle_id": "evidenceBundleId",
        "evidence_claim_id": "evidenceClaimId",
        "manifest_commit_hash": "manifestCommitHash",
        "redaction_transform_version": "redactionTransformVersion",
        "schema_version": "schemaVersion",
        "signer_key_id": "signerKeyId",
        "subject_id": "subjectId",
        "subject_kind": "subjectKind",
        "supersedes_claim_id": "supersedesClaimId",
    },
    "GateDecision": {
        "actor_identity_hash": "actorIdentityHash",
        "cascade_on_block": "cascadeOnBlock",
        "decided_at": "decidedAt",
        "decided_by": "decidedBy",
        "decision_epoch": "decisionEpoch",
        "evidence_bundle_id": "evidenceBundleId",
        "failed_assertion_ids": "failedAssertionIds",
        "gate_decision_id": "gateDecisionId",
        "gate_id": "gateId",
        "manifest_commit_hash": "manifestCommitHash",
        "schema_version": "schemaVersion",
        "scope_id": "scopeId",
        "scope_type": "scopeType",
        "signature_key_id": "signatureKeyId",
        "strict_pass": "strictPass",
        "unmet_conditions": "unmetConditions",
    },
    "GateDecisionDraft": {
        "actor_identity_hash": "actorIdentityHash",
        "cancellation_reason": "cancellationReason",
        "cancelled_at": "cancelledAt",
        "draft_id": "draftId",
        "draft_kind": "draftKind",
        "eval_run_ids": "evalRunIds",
        "evidence_refs": "evidenceRefs",
        "gate_id": "gateId",
        "manifest_commit_hash": "manifestCommitHash",
        "release_sha": "releaseSha",
        "resolution_state": "resolutionState",
        "resolved_gate_decision_id": "resolvedGateDecisionId",
        "schema_version": "schemaVersion",
        "scope_id": "scopeId",
        "scope_type": "scopeType",
        "submitted_at": "submittedAt",
        "worker_id": "workerId",
    },
    "GatePolicy": {
        "baseline_selector": "baselineSelector",
        "blocking_severity": "blockingSeverity",
        "effective_at": "effectiveAt",
        "effective_until": "effectiveUntil",
        "flaky_quarantine_policy": "flakyQuarantinePolicy",
        "gate_id": "gateId",
        "gate_policy_id": "gatePolicyId",
        "policy_version": "policyVersion",
        "schema_version": "schemaVersion",
    },
    "GateRound": {
        "gate_decision_id": "gateDecisionId",
        "gate_id": "gateId",
        "gate_round_id": "gateRoundId",
        "initiated_at": "initiatedAt",
        "initiated_by": "initiatedBy",
        "initiation_reason": "initiationReason",
        "restart_predecessor": "restartPredecessor",
        "schema_version": "schemaVersion",
        "scope_id": "scopeId",
        "scope_type": "scopeType",
    },
    "GateRoundScopeState": {
        "created_at": "createdAt",
        "project_id": "projectId",
        "schema_version": "schemaVersion",
        "scope_id": "scopeId",
        "scope_kind": "scopeKind",
        "updated_at": "updatedAt",
    },
    "IdempotencyRecord": {
        "expires_at": "expiresAt",
        "first_seen_at": "firstSeenAt",
        "idempotency_key": "idempotencyKey",
        "project_id": "projectId",
        "request_digest": "requestDigest",
        "response_ref": "responseRef",
        "response_status": "responseStatus",
        "schema_version": "schemaVersion",
    },
    "Incident": {
        "affected_run_ids": "affectedRunIds",
        "cluster_signature_hash": "clusterSignatureHash",
        "created_at": "createdAt",
        "first_seen_at": "firstSeenAt",
        "incident_id": "incidentId",
        "last_seen_at": "lastSeenAt",
        "owner_email": "ownerEmail",
        "postmortem_ref": "postmortemRef",
        "project_id": "projectId",
        "promoted_to_regression": "promotedToRegression",
        "schema_version": "schemaVersion",
    },
    "Manifest": {
        "created_at": "createdAt",
        "manifest_id": "manifestId",
        "project_id": "projectId",
        "schema_version": "schemaVersion",
    },
    "ManifestVersion": {
        "commit_hash": "commitHash",
        "effective_at": "effectiveAt",
        "effective_until": "effectiveUntil",
        "manifest_id": "manifestId",
        "manifest_version_id": "manifestVersionId",
        "schema_version": "schemaVersion",
        "signature_key_id": "signatureKeyId",
        "signed_by": "signedBy",
    },
    "ModelCallSpan": {
        "cached_token_count": "cachedTokenCount",
        "cost_usd": "costUsd",
        "finish_reason": "finishReason",
        "http_status": "httpStatus",
        "input_digest": "inputDigest",
        "input_redaction_policy_version": "inputRedactionPolicyVersion",
        "latency_ms": "latencyMs",
        "model_signature": "modelSignature",
        "output_digest": "outputDigest",
        "provider_error_class": "providerErrorClass",
        "provider_error_code": "providerErrorCode",
        "reasoning_token_count": "reasoningTokenCount",
        "request_message_count": "requestMessageCount",
        "request_token_count": "requestTokenCount",
        "response_token_count": "responseTokenCount",
        "schema_contract_id": "schemaContractId",
        "schema_version": "schemaVersion",
        "span_id": "spanId",
        "structured_output_mode": "structuredOutputMode",
        "tool_choice_mode": "toolChoiceMode",
    },
    "RedactionPolicy": {
        "approver_user_id": "approverUserId",
        "created_at": "createdAt",
        "dpa_ref": "dpaRef",
        "org_id": "orgId",
        "raw_capture": "rawCapture",
        "redaction_policy_id": "redactionPolicyId",
        "schema_version": "schemaVersion",
    },
    "ReplayCase": {
        "created_at": "createdAt",
        "expected_assertion_ids": "expectedAssertionIds",
        "failure_signature_hash": "failureSignatureHash",
        "human_reviewed": "humanReviewed",
        "inputs_digest": "inputsDigest",
        "inputs_ref": "inputsRef",
        "project_id": "projectId",
        "replay_case_id": "replayCaseId",
        "reviewed_at": "reviewedAt",
        "reviewer_email": "reviewerEmail",
        "schema_version": "schemaVersion",
        "source_run_id": "sourceRunId",
    },
    "ReplayCaseScopeState": {
        "created_at": "createdAt",
        "project_id": "projectId",
        "schema_version": "schemaVersion",
        "scope_id": "scopeId",
        "scope_kind": "scopeKind",
        "updated_at": "updatedAt",
    },
    "ReplayFixture": {
        "allowed_in_replay": "allowedInReplay",
        "capture_clock": "captureClock",
        "created_at": "createdAt",
        "fixture_id": "fixtureId",
        "input_digest": "inputDigest",
        "model_signature": "modelSignature",
        "output_digest": "outputDigest",
        "output_ref": "outputRef",
        "redaction_policy_version": "redactionPolicyVersion",
        "refresh_policy": "refreshPolicy",
        "replay_case_id": "replayCaseId",
        "schema_version": "schemaVersion",
        "side_effect_class": "sideEffectClass",
        "source_span_id": "sourceSpanId",
    },
    "ReplayResult": {
        "created_at": "createdAt",
        "evidence_bundle_id": "evidenceBundleId",
        "failure_signature_match": "failureSignatureMatch",
        "fixture_hits": "fixtureHits",
        "fixture_misses": "fixtureMisses",
        "network_egress_denied": "networkEgressDenied",
        "replay_case_id": "replayCaseId",
        "replay_result_id": "replayResultId",
        "replay_run_id": "replayRunId",
        "sandbox_driver": "sandboxDriver",
        "sandbox_id": "sandboxId",
        "schema_version": "schemaVersion",
        "side_effect_approved": "sideEffectApproved",
        "side_effect_attempts": "sideEffectAttempts",
    },
    "RetrievalSpan": {
        "citation_coverage": "citationCoverage",
        "context_token_count": "contextTokenCount",
        "context_waste_tokens": "contextWasteTokens",
        "document_count": "documentCount",
        "duplicate_document_count": "duplicateDocumentCount",
        "empty_retrieval": "emptyRetrieval",
        "latency_ms": "latencyMs",
        "query_digest": "queryDigest",
        "query_redaction_policy_version": "queryRedactionPolicyVersion",
        "relevance_proxy_score": "relevanceProxyScore",
        "retriever_name": "retrieverName",
        "schema_version": "schemaVersion",
        "span_id": "spanId",
    },
    "RootCauseHypothesis": {
        "created_at": "createdAt",
        "evidence_refs": "evidenceRefs",
        "hypothesis_class": "hypothesisClass",
        "hypothesis_id": "hypothesisId",
        "promoted_to_replay_case_id": "promotedToReplayCaseId",
        "reviewer_decision": "reviewerDecision",
        "reviewer_email": "reviewerEmail",
        "run_id": "runId",
        "schema_version": "schemaVersion",
        "span_id": "spanId",
    },
    "RunResult": {
        "actor_identity_hash": "actorIdentityHash",
        "decided_at": "decidedAt",
        "decision_epoch": "decisionEpoch",
        "error_priority_rule": "errorPriorityRule",
        "evidence_bundle_id": "evidenceBundleId",
        "manifest_commit_hash": "manifestCommitHash",
        "primary_failure_class": "primaryFailureClass",
        "project_id": "projectId",
        "run_id": "runId",
        "run_result_id": "runResultId",
        "schema_version": "schemaVersion",
        "signature_key_id": "signatureKeyId",
        "written_by": "writtenBy",
    },
    "RunScopeState": {
        "created_at": "createdAt",
        "project_id": "projectId",
        "schema_version": "schemaVersion",
        "scope_id": "scopeId",
        "scope_kind": "scopeKind",
        "updated_at": "updatedAt",
    },
    "Span": {
        "ended_at": "endedAt",
        "error_class": "errorClass",
        "parent_span_id": "parentSpanId",
        "run_id": "runId",
        "schema_version": "schemaVersion",
        "span_id": "spanId",
        "span_type": "spanType",
        "started_at": "startedAt",
    },
    "ToolCallSpan": {
        "args_digest": "argsDigest",
        "args_redaction_policy_version": "argsRedactionPolicyVersion",
        "args_schema_contract_id": "argsSchemaContractId",
        "args_validation_outcome": "argsValidationOutcome",
        "latency_ms": "latencyMs",
        "marker_id": "markerId",
        "parallel_index": "parallelIndex",
        "result_digest": "resultDigest",
        "schema_version": "schemaVersion",
        "side_effect_class": "sideEffectClass",
        "span_id": "spanId",
        "tool_name": "toolName",
    },
}


def snake_to_camel(envelope: str) -> dict[str, str]:
    """Return the snake_case -> camelCase alias map for ``envelope``.

    If ``envelope`` is not in the canonical envelope set, returns an empty
    dict (no aliases known).
    """
    return dict(FIELD_ALIASES_BY_ENVELOPE.get(envelope, {}))


def camel_to_snake(envelope: str) -> dict[str, str]:
    """Return the camelCase -> snake_case alias map for ``envelope``.

    Inverse of ``snake_to_camel``.
    """
    fwd = FIELD_ALIASES_BY_ENVELOPE.get(envelope, {})
    return {v: k for k, v in fwd.items()}


__all__ = [
    "FIELD_ALIASES_BY_ENVELOPE",
    "snake_to_camel",
    "camel_to_snake",
]
