// RFC 8785 JSON Canonicalization Scheme (JCS) serializer (TypeScript).
//
// Mirror of packages/contracts/src/relay_contracts/canonical.py. Output
// bytes MUST be byte-equal to the cel-python module's `jcs_canonicalize`
// output for the same input value (VAL-W6-014). The cross-language
// parity test reads fixtures generated by the Python side and asserts
// `bytes(py_output) == bytes(ts_output)` for every entry.
//
// Why not stdlib JSON? `JSON.stringify` does not sort keys, and its
// number formatter for floats matches ECMA-262 ToString (which JCS
// requires) only by coincidence -- whole-valued doubles like 1.0 stringify
// to "1" in JS but the Python `repr(1.0)` is "1.0", so the Python encoder
// has special-case handling. The TS encoder pins the contract directly:
//   - keys sorted by UTF-16 code-unit sequence (RFC 8785 section 3.2.3)
//   - numbers via ECMA-262 7.1.12.1 ToString (JS native; no special-case)
//   - strings escape only `"`, `\\`, U+0000..U+001F (RFC 8785 section 3.2.2.1)
//   - NaN / +Inf / -Inf rejected at serialisation (caller should reject earlier)
//
// Spec anchors: D, RFC 8785.
// Eng plan anchors: line 306 ("RFC 8785 JCS ... conformance suites").
//
// ASCII-only per CLAUDE.md "ASCII-Safe Source".

import { RelayCelNumericOutOfBoundsError } from "./errors.js";

// Round-3 P1 fix #5: wire-stable code for the BMP-only key screen.
// JS strings sort by UTF-16 code unit; Python strings sort by codepoint.
// For BMP keys (< U+10000) these match. For supplementary-plane keys
// (>= U+10000) they diverge -- the same input produces DIFFERENT
// canonical bytes between runtimes, silently breaking cross-runtime
// signature verification (CLAUDE.md keystone invariant #11). Until
// both encoders implement the full UTF-16-code-unit sort, both runtimes
// fail-closed on supplementary-plane KEYS. Values may contain
// supplementary-plane characters; only keys are sorted.
export const CANONICAL_NON_BMP_KEY_CODE = "RELAY-CANON-NON-BMP-KEY" as const;

export class CanonicalEncodingError extends Error {
  public readonly code: string;

  constructor(message: string, code: string = CANONICAL_NON_BMP_KEY_CODE) {
    super(message);
    this.name = "CanonicalEncodingError";
    this.code = code;
  }
}

// RFC 8785 section 3.2.2.1: control characters U+0000..U+001F MUST be
// escaped using the short forms or \\u00xx; quote and backslash also.
// The map mirrors packages/contracts/src/relay_contracts/canonical.py:36-47.
const ESCAPE_MAP: Record<number, string> = {
  0x00: "\\u0000", 0x01: "\\u0001", 0x02: "\\u0002", 0x03: "\\u0003",
  0x04: "\\u0004", 0x05: "\\u0005", 0x06: "\\u0006", 0x07: "\\u0007",
  0x08: "\\b",     0x09: "\\t",     0x0a: "\\n",     0x0b: "\\u000b",
  0x0c: "\\f",     0x0d: "\\r",     0x0e: "\\u000e", 0x0f: "\\u000f",
  0x10: "\\u0010", 0x11: "\\u0011", 0x12: "\\u0012", 0x13: "\\u0013",
  0x14: "\\u0014", 0x15: "\\u0015", 0x16: "\\u0016", 0x17: "\\u0017",
  0x18: "\\u0018", 0x19: "\\u0019", 0x1a: "\\u001a", 0x1b: "\\u001b",
  0x1c: "\\u001c", 0x1d: "\\u001d", 0x1e: "\\u001e", 0x1f: "\\u001f",
  0x22: '\\"',
  0x5c: "\\\\",
};

function encodeString(s: string): string {
  // RFC 8785 + spec line 5696 + VAL-W17-003: all canonicalized JSON
  // for digest uses UTF-8 NFC. JS String.prototype.normalize("NFC") is
  // ECMAScript-standard (ES6 / ECMA-402) and idempotent; ASCII strings
  // are fixed points. Mirrors the Python encoders'
  // unicodedata.normalize("NFC", s) call.
  s = s.normalize("NFC");
  // Iterate by code units (UTF-16). Code units 0x00-0x1F, 0x22, 0x5C
  // get escaped; everything else (including high surrogate pairs and
  // non-ASCII BMP code points) is emitted literally. The final UTF-8
  // encoding happens when TextEncoder converts the JS string to bytes.
  let out = '"';
  for (let i = 0; i < s.length; i++) {
    const cp = s.charCodeAt(i);
    const esc = ESCAPE_MAP[cp];
    if (esc !== undefined) {
      out += esc;
    } else {
      // String concatenation with the source character preserves the
      // exact code-unit sequence, including surrogate pairs. Use
      // String.fromCharCode(cp) instead of s[i] to satisfy
      // noUncheckedIndexedAccess (s[i] is typed as string | undefined
      // even though i < s.length is invariant in this loop).
      out += String.fromCharCode(cp);
    }
  }
  out += '"';
  return out;
}

function encodeNumber(n: number): string {
  if (!Number.isFinite(n)) {
    // Defensive: callers are expected to reject before reaching here.
    throw new RelayCelNumericOutOfBoundsError(
      `JCS cannot encode non-finite number: ${String(n)}`,
    );
  }
  // Negative zero collapses to "0" per ECMA-262 ToString.
  if (n === 0) {
    // Both +0 and -0 hit this branch; ECMA-262 ToString yields "0".
    return "0";
  }
  // ECMA-262 7.1.12.1 ToString applied to IEEE-754 doubles is what
  // JS Number.prototype.toString() implements. JCS section 3.2.2 also
  // mandates this representation, so the JS native form IS the JCS form
  // for finite, non-zero numbers. No special handling for whole-valued
  // floats: 1.0 in JS stringifies to "1" (matching Python's special
  // case in canonical.py:92-93).
  return String(n);
}

// Number used as a typeof check; Python's bool subclasses int, but in
// JS booleans are a separate primitive and never need the routing the
// Python encoder does at canonical.py:73-74.

function encode(value: unknown): string {
  if (value === null || value === undefined) {
    return "null";
  }
  const t = typeof value;
  if (t === "boolean") {
    return value ? "true" : "false";
  }
  if (t === "number") {
    return encodeNumber(value as number);
  }
  if (t === "bigint") {
    // BigInt is JCS-encodable as the decimal integer form. The Python
    // encoder accepts arbitrary-precision int via str(int). JS reaches
    // here when callers pass bigint explicitly. Negative zero is
    // unrepresentable in BigInt.
    return (value as bigint).toString(10);
  }
  if (t === "string") {
    return encodeString(value as string);
  }
  if (Array.isArray(value)) {
    const parts: string[] = [];
    for (const item of value) {
      parts.push(encode(item));
    }
    return "[" + parts.join(",") + "]";
  }
  if (t === "object") {
    // RFC 8785 section 3.2.3: keys sorted by their UTF-16 code-unit
    // sequence. JS string `<` operator compares by code unit, which
    // matches the spec for BMP. For supplementary-plane (>= U+10000)
    // characters JS compares by surrogate-pair code units while Python
    // sorts by codepoint -- divergent canonical bytes silently break
    // cross-runtime signature verification. Round-3 P1 fix #5: both
    // runtimes fail-closed on supplementary-plane KEYS. Values may
    // contain supplementary-plane characters; only keys are screened.
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj);
    for (const k of keys) {
      // for...of on a string iterates Unicode codepoints (surrogate
      // pairs collapse to a single iteration step yielding the full
      // codepoint via codePointAt(0)).
      for (const ch of k) {
        const cp = ch.codePointAt(0);
        if (cp !== undefined && cp >= 0x10000) {
          throw new CanonicalEncodingError(
            "JCS: non-BMP codepoint U+" +
              cp.toString(16).toUpperCase().padStart(4, "0") +
              " in object key " +
              JSON.stringify(k) +
              "; supplementary-plane keys produce runtime-divergent " +
              "canonical bytes and are refused. Re-key the object " +
              "with BMP-only strings.",
          );
        }
      }
    }
    const sortedKeys = keys.slice().sort();
    const parts: string[] = [];
    for (const k of sortedKeys) {
      // Object.keys returns own-enumerable string keys; values are
      // looked up explicitly to keep TS happy under
      // noUncheckedIndexedAccess.
      const v = obj[k];
      parts.push(encodeString(k) + ":" + encode(v));
    }
    return "{" + parts.join(",") + "}";
  }
  throw new TypeError(
    `JCS: unsupported type ${t} for value ${String(value)}`,
  );
}

const ENCODER = new TextEncoder();

/**
 * Return the RFC 8785 JCS canonical-bytes form of `value`.
 *
 * Output is UTF-8 bytes (no BOM). Caller is responsible for hashing or
 * cross-runtime comparison. NaN / +Inf / -Inf raise
 * `RelayCelNumericOutOfBoundsError` defensively; well-formed callers
 * reject these at the evaluation-result boundary.
 */
export function jcsCanonicalize(value: unknown): Uint8Array {
  return ENCODER.encode(encode(value));
}
