"""ACEF render module — human-readable compliance reports.

Generates Markdown and console-formatted compliance reports from Assessment Bundles.
"""

from __future__ import annotations


from acef.models.assessment import AssessmentBundle
from acef.models.enums import ProvisionOutcome, RuleOutcome


# Outcome display mapping
_OUTCOME_SYMBOLS = {
    ProvisionOutcome.SATISFIED: "[PASS]",
    ProvisionOutcome.NOT_SATISFIED: "[FAIL]",
    ProvisionOutcome.PARTIALLY_SATISFIED: "[PARTIAL]",
    ProvisionOutcome.GAP_ACKNOWLEDGED: "[GAP]",
    ProvisionOutcome.SKIPPED: "[SKIP]",
    ProvisionOutcome.NOT_ASSESSED: "[N/A]",
}

_RULE_OUTCOME_SYMBOLS = {
    RuleOutcome.PASSED: "[PASS]",
    RuleOutcome.FAILED: "[FAIL]",
    RuleOutcome.SKIPPED: "[SKIP]",
    RuleOutcome.ERROR: "[ERR]",
}


def render_markdown(assessment: AssessmentBundle) -> str:
    """Render an Assessment Bundle as a Markdown compliance report.

    Args:
        assessment: The AssessmentBundle to render.

    Returns:
        Markdown-formatted report string.
    """
    lines: list[str] = []

    lines.append("# ACEF Compliance Assessment Report")
    lines.append("")
    lines.append(f"**Assessment ID:** `{assessment.assessment_id}`")
    lines.append(f"**Timestamp:** {assessment.timestamp}")
    lines.append(f"**Evaluation Instant:** {assessment.evaluation_instant}")
    lines.append(f"**Assessor:** {assessment.assessor.name} v{assessment.assessor.version}")
    lines.append("")

    if assessment.evidence_bundle_ref.package_id:
        lines.append(f"**Evidence Bundle:** `{assessment.evidence_bundle_ref.package_id}`")
        if assessment.evidence_bundle_ref.content_hash:
            lines.append(f"**Bundle Digest:** `{assessment.evidence_bundle_ref.content_hash}`")
        lines.append("")

    # Profiles evaluated
    if assessment.profiles_evaluated:
        lines.append("## Profiles Evaluated")
        lines.append("")
        for profile in assessment.profiles_evaluated:
            lines.append(f"- {profile}")
        lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(assessment.summary())
    lines.append("")

    # Provision Summaries
    if assessment.provision_summary:
        lines.append("## Provision Results")
        lines.append("")
        lines.append("| Provision | Profile | Outcome | Fails | Warnings | Skipped |")
        lines.append("|-----------|---------|---------|-------|----------|---------|")
        for ps in assessment.provision_summary:
            symbol = _OUTCOME_SYMBOLS.get(ps.provision_outcome, "[?]")
            lines.append(
                f"| {ps.provision_id} | {ps.profile_id} | {symbol} {ps.provision_outcome.value} "
                f"| {ps.fail_count} | {ps.warning_count} | {ps.skipped_count} |"
            )
        lines.append("")

    # Rule Details
    if assessment.results:
        lines.append("## Rule Details")
        lines.append("")
        for result in assessment.results:
            symbol = _RULE_OUTCOME_SYMBOLS.get(result.outcome, "[?]")
            severity_label = f"[{result.rule_severity.value.upper()}]"
            lines.append(f"### {result.rule_id}")
            lines.append(f"- **Provision:** {result.provision_id}")
            lines.append(f"- **Severity:** {severity_label}")
            lines.append(f"- **Outcome:** {symbol} {result.outcome.value}")
            if result.message:
                lines.append(f"- **Message:** {result.message}")
            if result.evidence_refs:
                lines.append(f"- **Evidence:** {', '.join(f'`{r}`' for r in result.evidence_refs[:5])}")
            lines.append("")

    # Structural Errors
    if assessment.structural_errors:
        lines.append("## Structural Errors")
        lines.append("")
        for error in assessment.structural_errors:
            code = error.get("code", "")
            msg = error.get("message", "")
            severity = error.get("severity", "")
            path = error.get("path", "")
            lines.append(f"- **{code}** [{severity}]: {msg}")
            if path:
                lines.append(f"  - Path: `{path}`")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by ACEF Reference Validator*")

    return "\n".join(lines)


def render_console(assessment: AssessmentBundle) -> str:
    """Render a concise console-formatted summary.

    Args:
        assessment: The AssessmentBundle to render.

    Returns:
        Console-formatted string with ANSI-compatible markers.
    """
    lines: list[str] = []

    lines.append("ACEF Compliance Assessment")
    lines.append("=" * 40)
    lines.append(f"Bundle: {assessment.evidence_bundle_ref.package_id}")
    lines.append(f"Evaluated: {assessment.evaluation_instant}")
    lines.append("")

    # Summary
    lines.append(assessment.summary())
    lines.append("")

    # Provision table
    if assessment.provision_summary:
        lines.append("Provisions:")
        for ps in assessment.provision_summary:
            symbol = _OUTCOME_SYMBOLS.get(ps.provision_outcome, "[?]")
            lines.append(f"  {symbol:10s} {ps.provision_id} ({ps.profile_id})")

    # Failed rules
    failed_rules = [r for r in assessment.results if r.outcome == RuleOutcome.FAILED]
    if failed_rules:
        lines.append("")
        lines.append(f"Failed Rules ({len(failed_rules)}):")
        for r in failed_rules:
            lines.append(f"  [{r.rule_severity.value.upper():7s}] {r.rule_id}: {r.message or 'No message'}")

    # Errors
    if assessment.structural_errors:
        lines.append("")
        lines.append(f"Structural Errors ({len(assessment.structural_errors)}):")
        for error in assessment.structural_errors[:10]:
            lines.append(f"  {error.get('code', '')}: {error.get('message', '')}")
        if len(assessment.structural_errors) > 10:
            lines.append(f"  ... and {len(assessment.structural_errors) - 10} more")

    return "\n".join(lines)
