"""``local_two_layer_locked_write`` (Local OSS profile state primitive).

Spec H lines 4163-4180:

    # Local-profile equivalent: two-layer lock around state files.
    # Inspired directly by the SRP system paper's StateStore (Vaughn, 2026):
    # in-process threading.RLock outermost + OS-level fcntl.flock inside,
    # with a 5-second timeout that raises StateLockTimeout rather than hanging.
    # Lock order is fixed (RLock outer, file-lock inner) to avoid deadlock between
    # the local control-plane process and a co-resident UI/inspector process.
    def local_two_layer_locked_write(
        *, path: str, body_writer: Callable[[BinaryIO], None],
        timeout_seconds: float = 5.0
    ) -> PersistResult:
        ...

Used by the Local OSS profile control-plane for runner state, event log,
and the offline verifier's scratch space. Hosted Postgres profile uses
``transactional_db_write`` instead.

Lock layering (load-bearing per spec lines 4167-4172):

    OUTERMOST: ``threading.RLock``, looked up from a module-level
               per-canonical-path registry. Provides mutual exclusion
               between in-process threads that target the same path.
               Reentrant so the same thread may call the primitive
               recursively on the same path without deadlocking.

    INNERMOST: ``portalocker.Lock`` on a STABLE sibling lock file
               ``.<destname>.wlock``. Provides mutual exclusion between
               OS processes (the sidecar + co-resident inspector / UI).
               Wrapped in a deadline loop so the 5-second timeout
               manifests as ``StateLockTimeout`` rather than a hang.

Release order is the strict reverse: portalocker first, RLock second.

PersistResult.event_id binding (VAL-V2M03-022): every successful write
returns a ``PersistResult`` with a non-null ``event_id``. The full
event_log_entries row append is the responsibility of the caller's
composition layer (the local-OSS event log writer); the primitive itself
generates the event_id so the caller has a stable correlation key BEFORE
emitting the audit row.

The destination write itself uses the SAME write-tmp + fsync + atomic
rename pattern as ``local_atomic_file_write`` so concurrent inspectors
never observe a partially-written file. The body is written via a
``body_writer`` callback that receives an open binary file handle; this
matches the spec H signature (``Callable[[BinaryIO], None]``) and lets the
caller stream large payloads without materializing them as a single bytes
object.

CLAUDE.md keystone invariants honored:

  #8 Atomic persistence -- this primitive is one of the four sanctioned
  write paths for Local OSS profile state. CI lint (VAL-V2M03-023)
  forbids direct ``open(..., 'w')`` inside the sidecar tree outside
  the primitive implementations.

ASCII-only per CLAUDE.md "ASCII-Safe Source".
"""

from __future__ import annotations

import contextlib
import os
import tempfile
import threading
import time
import uuid
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO, cast

import portalocker

from .errors import StateLockTimeout

# ---------------------------------------------------------------------------
# PersistResult
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PersistResult:
    """Return type for the local two-layer locked write primitive.

    Spec H line 4196: "Every primitive returns PersistResult with event_id."
    The event_id is generated by the primitive at write commit time so the
    caller has a stable correlation key for the subsequent event_log_entries
    row append.

    Attributes:
        event_id: UUID4 string assigned at successful write commit. The
            caller composes the event_log_entries row using this id so the
            row binds back to the precise atomic write.
        path: Resolved destination path (absolute, str form). Useful for
            diagnostics and the caller's audit-row payload.
        bytes_written: Size of the payload written. Surfaced so callers
            can populate evidence-bundle byte counts without re-stat'ing
            the destination.
    """

    event_id: str
    path: str
    bytes_written: int


# ---------------------------------------------------------------------------
# In-process RLock registry (OUTER layer)
# ---------------------------------------------------------------------------
#
# A module-level dict of per-canonical-path RLocks. Keyed by the absolute
# resolved string form of the destination path so that two threads writing
# the same path serialize, while two threads writing DIFFERENT paths run
# in parallel. The registry itself is guarded by a dedicated meta-lock so
# concurrent dict.setdefault races don't construct duplicate RLocks.
#
# A bare ``threading.RLock()`` constructed inside the function body would
# create a new lock per call and defeat mutual exclusion -- this registry
# is the load-bearing structure that delivers cross-call serialization.

_RLOCK_REGISTRY: dict[str, threading.RLock] = {}
_REGISTRY_META_LOCK = threading.Lock()


def _get_rlock_for(canonical_path: str) -> threading.RLock:
    """Return the per-path RLock, creating one on first observation."""
    # Fast path: no meta-lock if entry already exists.
    existing = _RLOCK_REGISTRY.get(canonical_path)
    if existing is not None:
        return existing
    # Slow path: take meta-lock and double-check.
    with _REGISTRY_META_LOCK:
        existing = _RLOCK_REGISTRY.get(canonical_path)
        if existing is not None:
            return existing
        lock = threading.RLock()
        _RLOCK_REGISTRY[canonical_path] = lock
        return lock


def _reset_rlock_registry_for_tests() -> None:
    """Test-only: clear the per-path RLock registry.

    Tests that monkeypatch ``threading.RLock`` need a way to evict the
    cached real-RLock instances so the next ``_get_rlock_for`` call
    constructs a fresh (patched) lock. Production code MUST NOT call this.
    """
    with _REGISTRY_META_LOCK:
        _RLOCK_REGISTRY.clear()


# ---------------------------------------------------------------------------
# Sibling lock file (INNER layer support)
# ---------------------------------------------------------------------------


def _sibling_lock_path(destination: Path | str) -> str:
    """Return the canonical sibling lock-file path for ``destination``.

    The lock file lives next to the destination as
    ``.<destname>.wlock`` (leading dot keeps it out of the ``destname.``
    mkstemp prefix space so recovery sweeps that unlink stale tempfiles
    do not unlink the live lock). The lock file's inode is created ONCE
    and never renamed, providing a single consistent serialization
    point even though the destination's inode swaps on every atomic
    rename.
    """
    dest = Path(destination)
    return str(dest.parent / ("." + dest.name + ".wlock"))


def _ensure_lock_file(lock_path: str) -> None:
    """Create the sibling lock file if it does not already exist."""
    if Path(lock_path).exists():
        return
    with contextlib.suppress(FileExistsError):
        # ``os.O_CLOEXEC`` is POSIX-only; Windows lacks the
        # exec-inheritance model the flag controls. Use 0 (no-op) on
        # Windows so the open succeeds without the missing attribute.
        cloexec_flag = getattr(os, "O_CLOEXEC", 0)
        fd = os.open(
            lock_path,
            os.O_CREAT | os.O_RDWR | cloexec_flag,
            0o600 if os.name != "nt" else 0o666,
        )
        os.close(fd)


# ---------------------------------------------------------------------------
# Primitive
# ---------------------------------------------------------------------------


def local_two_layer_locked_write(
    *,
    path: Path | str,
    body_writer: Callable[[BinaryIO], None],
    timeout_seconds: float = 5.0,
) -> PersistResult:
    """Atomic two-layer locked write to ``path``.

    Lock order (load-bearing per spec lines 4167-4172):

        1. Acquire per-path ``threading.RLock`` (OUTER)
        2. Acquire ``portalocker.Lock`` on sibling lock file (INNER)
        3. Write payload via body_writer to sibling tempfile + fsync
        4. Atomic rename tempfile -> destination
        5. Release portalocker (INNER)
        6. Release RLock (OUTER)

    Args:
        path: Destination file path. Parent directory MUST exist.
        body_writer: Callback that receives an open binary file handle
            and writes the payload bytes to it. The callback runs while
            BOTH lock layers are held.
        timeout_seconds: Maximum wall-clock to wait for EITHER lock
            layer. Default 5.0 per spec H. Raises ``StateLockTimeout``
            (not a generic OSError) on timeout so callers can pattern-
            match on the structured failure.

    Returns:
        PersistResult with a UUID4 ``event_id``, the resolved destination
        path, and the bytes-written count.

    Raises:
        StateLockTimeout: either lock layer not acquired within
            ``timeout_seconds``.
        FileNotFoundError: parent directory missing.
        PermissionError: filesystem refused the rename or open.
        OSError: any other I/O failure.
        TypeError: ``body_writer`` is not callable.
    """
    if not callable(body_writer):
        raise TypeError(
            "local_two_layer_locked_write: 'body_writer' must be callable; "
            f"got {type(body_writer).__name__}"
        )

    destination = Path(path)
    parent = destination.parent
    if not parent.is_dir():
        raise FileNotFoundError(
            f"local_two_layer_locked_write: parent directory missing: {parent}"
        )

    # Canonicalize the destination path for the registry key. We use
    # ``os.path.abspath`` (not ``resolve``) so we do not follow symlinks --
    # two callers naming the destination via different symlink paths SHOULD
    # serialize on the SAME RLock, but ``resolve`` would also require the
    # destination to exist (it does not, until the first write commits).
    canonical = os.path.abspath(str(destination))

    # OUTER: in-process RLock (acquired FIRST so the AST scan + runtime
    # ordering test see RLock-then-portalocker).
    rlock = _get_rlock_for(canonical)
    rlock_acquired = rlock.acquire(timeout=timeout_seconds)
    if not rlock_acquired:
        raise StateLockTimeout(
            "timed out waiting for in-process RLock",
            layer="rlock",
            timeout_seconds=timeout_seconds,
            path=canonical,
        )

    try:
        # INNER: portalocker file lock on the stable sibling lock file.
        # portalocker's Lock context manager accepts a ``timeout`` kwarg in
        # non-blocking mode (LOCK_EX | LOCK_NB), but the ergonomic way to
        # achieve a wall-clock deadline is to roll our own LOCK_NB loop --
        # the LOCK_NB path raises LockException immediately on contention,
        # so we sleep+retry until the deadline. This keeps the inner-layer
        # timeout deterministic and observable as StateLockTimeout.
        lock_path = _sibling_lock_path(destination)
        _ensure_lock_file(lock_path)

        deadline = time.monotonic() + timeout_seconds
        # The non-blocking flag combination differs slightly across
        # portalocker versions; ``LOCK_EX | LOCK_NB`` is the portable form.
        nb_flags = portalocker.LOCK_EX | portalocker.LOCK_NB

        # We construct one ``portalocker.Lock`` per attempt because the
        # context manager treats failed acquisition as a terminal state and
        # is not safe to retry on the same instance across iterations.
        #
        # ``fail_when_locked=True`` (combined with LOCK_NB) makes portalocker
        # raise ``AlreadyLocked`` IMMEDIATELY on contention rather than
        # internally retrying for its own default 5-second timeout. We roll
        # our own retry loop bounded by the caller-provided
        # ``timeout_seconds`` so the deadline is deterministic.
        attempt_delay = 0.01
        while True:
            inner = portalocker.Lock(
                lock_path,
                mode="ab",
                flags=nb_flags,
                fail_when_locked=True,
                timeout=0,
            )
            try:
                inner.__enter__()
            except portalocker.exceptions.LockException:
                # Inner lock currently held by another process. Sleep and
                # retry until the deadline expires.
                now = time.monotonic()
                if now >= deadline:
                    raise StateLockTimeout(
                        "timed out waiting for portalocker file lock",
                        layer="portalocker",
                        timeout_seconds=timeout_seconds,
                        path=canonical,
                    ) from None
                remaining = deadline - now
                time.sleep(min(attempt_delay, remaining))
                # Exponential backoff capped at 100ms so high-contention
                # cases still poll the lock often enough to win promptly
                # when it is released.
                attempt_delay = min(attempt_delay * 2, 0.1)
                continue
            else:
                # Inner lock acquired; do the write under BOTH layers.
                try:
                    bytes_written = _write_atomic_via_callback(
                        destination=destination,
                        parent=parent,
                        body_writer=body_writer,
                    )
                finally:
                    inner.__exit__(None, None, None)
                # Inner lock released BEFORE outer lock per spec ordering.
                event_id = str(uuid.uuid4())
                return PersistResult(
                    event_id=event_id,
                    path=canonical,
                    bytes_written=bytes_written,
                )
    finally:
        rlock.release()


# ---------------------------------------------------------------------------
# Atomic write helper (write-tmp + fsync + rename, mirrors local_atomic_file_write)
# ---------------------------------------------------------------------------


def _write_atomic_via_callback(
    *,
    destination: Path,
    parent: Path,
    body_writer: Callable[[BinaryIO], None],
) -> int:
    """Write payload via ``body_writer`` to a sibling tempfile then rename.

    Returns the number of bytes written. Uses ``os.replace`` for atomic
    rename on both POSIX and Windows. Applies 0o600 on POSIX before the
    rename so the destination never appears world-readable.
    """
    fd, tmp_name = tempfile.mkstemp(
        prefix=destination.name + ".",
        dir=str(parent),
    )
    bytes_written = 0
    try:
        # Use a counting wrapper so we can return the exact byte count.
        with os.fdopen(fd, "wb") as raw_fh:
            counter = _CountingBinaryWriter(raw_fh)
            # The counter duck-types the BinaryIO surface the callback uses
            # (write/flush/fileno); cast reflects the documented invariant.
            body_writer(cast("BinaryIO", counter))
            raw_fh.flush()
            os.fsync(raw_fh.fileno())
            bytes_written = counter.bytes_written
        if os.name != "nt":
            os.chmod(tmp_name, 0o600)
        os.replace(tmp_name, str(destination))
    except BaseException:
        with contextlib.suppress(FileNotFoundError):
            os.unlink(tmp_name)
        raise
    return bytes_written


class _CountingBinaryWriter:
    """Tiny wrapper that counts bytes written via ``write``.

    The body_writer callback receives this object (which behaves like a
    BinaryIO file handle) so we can surface ``bytes_written`` in the
    returned PersistResult without re-stat'ing the destination after
    rename.
    """

    def __init__(self, inner: BinaryIO) -> None:
        self._inner = inner
        self.bytes_written = 0

    def write(self, data: bytes) -> int:
        n = self._inner.write(data)
        # ``write`` may return None on some BinaryIO subclasses; fall back
        # to len(data) for the byte count in that case.
        self.bytes_written += int(n) if n is not None else len(data)
        return n if n is not None else len(data)

    def flush(self) -> None:
        self._inner.flush()

    def fileno(self) -> int:
        return self._inner.fileno()


__all__ = [
    "PersistResult",
    "local_two_layer_locked_write",
]
