// VAL-W6-014: cel-js canonical output uses RFC 8785 JCS
//             (byte-identical to cel-python).
//
// For every entry in the conformance corpus, the JCS-canonicalised
// byte-string produced by the cel-js evaluator MUST equal the JCS bytes
// produced by cel-python. Comparison is `bytes(py_output) ==
// bytes(ts_output)` read from corpus fixture files -- no normalisation
// step in between.
//
// Tool: conformance-corpus.
// Evidence: conformance-corpus exit code, per-case digest pair
// (`sha256(py_bytes)`, `sha256(ts_bytes)`), zero mismatches.
//
// ASCII-only per CLAUDE.md "ASCII-Safe Source".

import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, test } from "vitest";

import { jcsCanonicalize } from "../src/index.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PKG_ROOT = resolve(__dirname, "..");
const REPO_ROOT = resolve(PKG_ROOT, "..", "..");
const PARITY_PATH = resolve(
  REPO_ROOT,
  "tests",
  "conformance",
  "cel",
  "parity_fixtures.json",
);

interface ParityCase {
  name: string;
  // Python-side JCS canonical bytes encoded as a base64 string. Storing
  // bytes directly (not a re-canonicalised JSON value) is the only way
  // to make this test load-bearing -- if we stored only the input value
  // and re-ran Python at test time, we would never catch a divergence
  // between the encoders.
  py_jcs_b64: string;
  // The input value (already JSON-decoded into a JS-native shape).
  // Tests apply jcsCanonicalize to this input and assert the resulting
  // bytes match py_jcs_b64.
  input: unknown;
}

interface ParityFixtures {
  schema_version: string;
  cases: ParityCase[];
}

describe("VAL-W6-014: JCS bytes are byte-identical to cel-python", () => {
  test("a known-good fixed input matches the Python golden inline", () => {
    // Belt-and-suspenders: even if the parity fixture file is missing
    // we still pin one inline case identical to the Python test
    // test_jcs_known_digest_for_fixed_input
    // (test_w6_1_evaluator.py:330-348).
    const payload = {
      name: "relay",
      ok: true,
      count: 3,
      items: [1, 2, 3],
    };
    const out = jcsCanonicalize(payload);
    const expected = new TextEncoder().encode(
      '{"count":3,"items":[1,2,3],"name":"relay","ok":true}',
    );
    expect(Buffer.from(out)).toEqual(Buffer.from(expected));
  });

  test("number representation pins (whole-valued double, negative zero, integer)", () => {
    expect(Buffer.from(jcsCanonicalize(1.0))).toEqual(Buffer.from("1"));
    expect(Buffer.from(jcsCanonicalize(-0))).toEqual(Buffer.from("0"));
    expect(Buffer.from(jcsCanonicalize(0))).toEqual(Buffer.from("0"));
    expect(Buffer.from(jcsCanonicalize(-1))).toEqual(Buffer.from("-1"));
  });

  test("keys sorted lexicographically (UTF-16 code-unit order)", () => {
    const out = jcsCanonicalize({ b: 1, a: 2, c: 3 });
    expect(Buffer.from(out)).toEqual(Buffer.from('{"a":2,"b":1,"c":3}'));
  });

  test("only required control chars and quote/backslash are escaped", () => {
    expect(Buffer.from(jcsCanonicalize('a"b\\c'))).toEqual(
      Buffer.from('"a\\"b\\\\c"'),
    );
    expect(Buffer.from(jcsCanonicalize("\n"))).toEqual(Buffer.from('"\\n"'));
    // U+007F (DEL) is NOT escaped (above the control-char range).
    // Output bytes: 0x22, 0x7f, 0x22 -- the DEL byte literally
    // between quotes.
    expect(Buffer.from(jcsCanonicalize("\x7f"))).toEqual(
      Buffer.from([0x22, 0x7f, 0x22]),
    );
  });

  test("NaN / +Inf / -Inf raise at canonicalisation time", () => {
    expect(() => jcsCanonicalize(Number.NaN)).toThrow();
    expect(() => jcsCanonicalize(Number.POSITIVE_INFINITY)).toThrow();
    expect(() => jcsCanonicalize(Number.NEGATIVE_INFINITY)).toThrow();
  });

  test("output is Uint8Array (bytes), not string", () => {
    const out = jcsCanonicalize({ a: 1 });
    expect(out).toBeInstanceOf(Uint8Array);
  });

  test("cross-language parity fixtures: every case matches cel-python bytes", () => {
    if (!existsSync(PARITY_PATH)) {
      // The parity fixture file is generated by the W6.2 Python helper
      // script (scripts/generate-cel-parity-fixtures.py). If it is
      // missing the test fails informatively rather than silently
      // skipping -- a missing fixture is a P0 regression.
      throw new Error(
        `VAL-W6-014: parity fixture file is missing: ${PARITY_PATH}. ` +
          "Run 'uv run python scripts/generate-cel-parity-fixtures.py' to regenerate.",
      );
    }
    const text = readFileSync(PARITY_PATH, "utf-8");
    const fixtures = JSON.parse(text) as ParityFixtures;
    expect(fixtures.schema_version).toBe("relay.cel.parity_fixtures.v1");
    expect(fixtures.cases.length).toBeGreaterThan(0);
    const mismatches: { name: string; py_sha: string; ts_sha: string }[] = [];
    for (const c of fixtures.cases) {
      const tsBytes = jcsCanonicalize(c.input);
      const pyBytes = Buffer.from(c.py_jcs_b64, "base64");
      const tsSha = createHash("sha256").update(tsBytes).digest("hex");
      const pySha = createHash("sha256").update(pyBytes).digest("hex");
      if (tsSha !== pySha) {
        mismatches.push({ name: c.name, py_sha: pySha, ts_sha: tsSha });
      }
    }
    expect(mismatches).toEqual([]);
  });
});
