"""Shared fixtures and helpers for the W10.4 bundle-validator tests.

Provides a small fixture-builder API:

    build_bundle(*, claims, signer_key_id, decided_at, trust_anchor,
                 tsa_token=..., log_inclusion_proof=..., merkle=True)
        -> (bundle_dict, jwks, ...)

The helper creates a deterministic Ed25519 keypair (in-memory; never
written to disk so banned pattern #14 is preserved), signs the canonical
JCS bytes of the bundle payload, builds the Merkle root over claim
digests, and assembles the structured bundle dict.

w9-2 additions:
  * The fixture builder now generates an ephemeral ECDSA P-256 TSA root
    + leaf cert pair AT TEST TIME (private key material lives only in
    process memory) and signs a real RFC 3161 ``TimeStampResp`` over
    the bundle binding digest. The signed DER blob is base64url-encoded
    into the token's ``tsr_der_b64u`` field so the cryptographic
    verifier in ``relay_verifier.tsa.validate_tsa_token`` can decode +
    verify it end-to-end.
  * :class:`BuiltBundle` carries ``tsa_extra_roots_pem`` -- the PEM of
    the ephemeral root -- so each test passes it via
    ``ValidateBundleOptions(tsa_extra_trusted_roots_pem=...)``. The
    real wheel-bundled chain is still consulted; the ephemeral root is
    *additional* trust material for the test.

These helpers are imported by test_w10_4_*.py modules. They are test-
only fixtures and do NOT leak private-key bytes onto disk.

ASCII-only per CLAUDE.md "ASCII-Safe Source".
"""

from __future__ import annotations

import base64
import datetime as _dt
import hashlib
from dataclasses import dataclass, field
from typing import Any

from asn1crypto import algos as _asn1_algos
from asn1crypto import cms as _asn1_cms
from asn1crypto import core as _asn1_core
from asn1crypto import tsp as _asn1_tsp
from asn1crypto import x509 as _asn1_x509
from cryptography import x509 as _cx509
from cryptography.hazmat.primitives import hashes as _hashes
from cryptography.hazmat.primitives import serialization as _serialization
from cryptography.hazmat.primitives.asymmetric import ec as _ec
from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.x509.oid import ExtendedKeyUsageOID as _EKUOID
from cryptography.x509.oid import NameOID as _NameOID
from relay_verifier import (
    build_inclusion_proof,
    bundle_digest,
    canonical_json_bytes,
    compute_merkle_root,
    jwk_from_ed25519_public_key,
    sign_payload_ed25519,
)

# RFC 3161 id-ct-TSTInfo content-type OID.
_TST_INFO_OID = "1.2.840.113549.1.9.16.1.4"


def _b64u_encode(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode("ascii")


@dataclass
class BuiltBundle:
    """Container for a built test bundle + matching JWKS + signing key.

    The ``tsa_extra_roots_pem`` field carries the PEM-encoded ephemeral
    TSA root generated by the fixture builder. Tests pass this via
    ``ValidateBundleOptions(tsa_extra_trusted_roots_pem=...)`` so the
    real RFC 3161 ``TimeStampResp`` attached to the bundle verifies
    against the test root. The wheel-bundled placeholder root cannot
    sign tokens (no private key in the OSS tree per banned pattern #14),
    so tests must supply their own ephemeral root.
    """

    bundle: dict[str, Any]
    jwks: dict[str, Any]
    signing_key: ed25519.Ed25519PrivateKey
    witness_key: ed25519.Ed25519PrivateKey
    bundle_digest_hex: str
    tsa_extra_roots_pem: bytes = field(default=b"")


def make_keypair(seed: bytes) -> ed25519.Ed25519PrivateKey:
    """Deterministic Ed25519 keypair from a 32-byte seed."""
    if len(seed) != 32:
        raise ValueError(f"seed must be 32 bytes, got {len(seed)}")
    return ed25519.Ed25519PrivateKey.from_private_bytes(seed)


# ---------------------------------------------------------------------------
# Ephemeral TSA root + leaf cert generation (private key in memory only)
# ---------------------------------------------------------------------------


def _make_test_tsa_chain(
    *,
    cert_validity_window_seconds: int = 365 * 24 * 3600,
) -> tuple[_ec.EllipticCurvePrivateKey, _cx509.Certificate, _cx509.Certificate]:
    """Generate an ephemeral root + TSA-signer leaf pair for tests.

    Returns ``(leaf_private_key, leaf_cert, root_cert)``. The root is
    self-signed; the leaf is issued by the root and carries the
    ``id-kp-timeStamping`` extended key usage (required by RFC 3161
    verifiers like rfc3161_client's PKCS#7 backend).
    """
    now = _dt.datetime.now(_dt.UTC)
    not_before = now - _dt.timedelta(seconds=cert_validity_window_seconds)
    not_after = now + _dt.timedelta(seconds=cert_validity_window_seconds)

    # Root (CA).
    root_sk = _ec.generate_private_key(_ec.SECP256R1())
    root_subj = _cx509.Name([
        _cx509.NameAttribute(_NameOID.COMMON_NAME, "Relay Test Ephemeral TSA Root"),
        _cx509.NameAttribute(_NameOID.ORGANIZATION_NAME, "Epochly, Inc. (test)"),
    ])
    root_cert = (
        _cx509.CertificateBuilder()
        .subject_name(root_subj)
        .issuer_name(root_subj)
        .public_key(root_sk.public_key())
        .serial_number(_cx509.random_serial_number())
        .not_valid_before(not_before)
        .not_valid_after(not_after)
        .add_extension(
            _cx509.BasicConstraints(ca=True, path_length=None), critical=True,
        )
        .add_extension(
            _cx509.KeyUsage(
                digital_signature=False,
                content_commitment=False,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=True,
                crl_sign=True,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .sign(root_sk, _hashes.SHA256())
    )

    # Leaf (TSA signer) issued by root.
    leaf_sk = _ec.generate_private_key(_ec.SECP256R1())
    leaf_subj = _cx509.Name([
        _cx509.NameAttribute(_NameOID.COMMON_NAME, "Relay Test Ephemeral TSA Signer"),
        _cx509.NameAttribute(_NameOID.ORGANIZATION_NAME, "Epochly, Inc. (test)"),
    ])
    leaf_cert = (
        _cx509.CertificateBuilder()
        .subject_name(leaf_subj)
        .issuer_name(root_subj)
        .public_key(leaf_sk.public_key())
        .serial_number(_cx509.random_serial_number())
        .not_valid_before(not_before)
        .not_valid_after(not_after)
        .add_extension(
            _cx509.BasicConstraints(ca=False, path_length=None), critical=True,
        )
        .add_extension(
            _cx509.KeyUsage(
                digital_signature=True,
                content_commitment=False,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=False,
                crl_sign=False,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .add_extension(
            _cx509.ExtendedKeyUsage([_EKUOID.TIME_STAMPING]), critical=True,
        )
        .sign(root_sk, _hashes.SHA256())
    )

    return leaf_sk, leaf_cert, root_cert


def _build_real_tsr_der(
    *,
    leaf_sk: _ec.EllipticCurvePrivateKey,
    leaf_cert: _cx509.Certificate,
    bundle_digest_hex: str,
    gen_time_iso_z: str,
    policy_oid: str = "1.3.6.1.4.1.601.10.3.1",
    serial_number: int = 424242,
) -> bytes:
    """Build a real RFC 3161 ``TimeStampResp`` DER signed by ``leaf_sk``.

    Mirrors the production TSA wire shape:
      * TSTInfo embeds the SHA-256 ``MessageImprint`` and ``genTime``.
      * SignedData wraps the TSTInfo DER as ``EncapsulatedContentInfo.content``
        (must be wrapped in :class:`asn1crypto.core.ParsableOctetString` to
        bypass asn1crypto's content_type-driven auto-parse path).
      * SignerInfo signs the DER-encoded signed-attributes set
        (``CMSAttributes``) with ECDSA-SHA-256 over the leaf key.
      * The leaf cert is embedded in ``SignedData.certificates`` so the
        verifier can match it via ``IssuerAndSerialNumber``.
    """
    bundle_digest_bytes = bytes.fromhex(bundle_digest_hex)
    gen_time_dt = _dt.datetime.fromisoformat(gen_time_iso_z[:-1] + "+00:00")

    tst_info = _asn1_tsp.TSTInfo()
    tst_info["version"] = 1
    tst_info["policy"] = policy_oid
    mi = _asn1_tsp.MessageImprint()
    mi["hash_algorithm"] = _asn1_algos.DigestAlgorithm({"algorithm": "sha256"})
    mi["hashed_message"] = bundle_digest_bytes
    tst_info["message_imprint"] = mi
    tst_info["serial_number"] = serial_number
    tst_info["gen_time"] = gen_time_dt
    tst_info_der = tst_info.dump()

    # Build the SignerInfo signed-attributes set (must include
    # content_type and message_digest per RFC 5652 sec 5.3).
    signing_time = _asn1_cms.Time(
        name="utc_time", value=gen_time_dt.replace(microsecond=0),
    )
    signed_attrs = _asn1_cms.CMSAttributes([
        _asn1_cms.CMSAttribute({
            "type": "content_type",
            "values": [_TST_INFO_OID],
        }),
        _asn1_cms.CMSAttribute({
            "type": "message_digest",
            "values": [hashlib.sha256(tst_info_der).digest()],
        }),
        _asn1_cms.CMSAttribute({
            "type": "signing_time",
            "values": [signing_time],
        }),
    ])
    signature_bytes = leaf_sk.sign(signed_attrs.dump(), _ec.ECDSA(_hashes.SHA256()))

    asn1_leaf = _asn1_x509.Certificate.load(
        leaf_cert.public_bytes(_serialization.Encoding.DER),
    )

    signer_info = _asn1_cms.SignerInfo()
    signer_info["version"] = "v1"
    signer_info["sid"] = _asn1_cms.SignerIdentifier(
        name="issuer_and_serial_number",
        value=_asn1_cms.IssuerAndSerialNumber({
            "issuer": asn1_leaf.issuer,
            "serial_number": asn1_leaf.serial_number,
        }),
    )
    signer_info["digest_algorithm"] = _asn1_algos.DigestAlgorithm(
        {"algorithm": "sha256"},
    )
    signer_info["signed_attrs"] = signed_attrs
    signer_info["signature_algorithm"] = _asn1_algos.SignedDigestAlgorithm(
        {"algorithm": "sha256_ecdsa"},
    )
    signer_info["signature"] = signature_bytes

    # EncapsulatedContentInfo: setitem-after-init avoids asn1crypto's
    # content_type-driven dict-parse path that mangles raw bytes.
    eci = _asn1_cms.EncapsulatedContentInfo()
    eci["content_type"] = _TST_INFO_OID
    eci["content"] = _asn1_core.ParsableOctetString(tst_info_der)

    sd = _asn1_cms.SignedData()
    sd["version"] = "v3"
    sd["digest_algorithms"] = [
        _asn1_algos.DigestAlgorithm({"algorithm": "sha256"}),
    ]
    sd["encap_content_info"] = eci
    sd["certificates"] = [
        _asn1_cms.CertificateChoices(name="certificate", value=asn1_leaf),
    ]
    sd["signer_infos"] = [signer_info]

    ci = _asn1_cms.ContentInfo()
    ci["content_type"] = "signed_data"
    ci["content"] = sd

    tsr = _asn1_tsp.TimeStampResp()
    tsr["status"] = _asn1_tsp.PKIStatusInfo({"status": "granted"})
    tsr["time_stamp_token"] = ci
    return tsr.dump()


def _build_tsa_token(
    *,
    bundle_digest_hex: str,
    gen_time: str,
    leaf_sk: _ec.EllipticCurvePrivateKey,
    leaf_cert: _cx509.Certificate,
    signer_subject: str | None = None,
) -> dict[str, Any]:
    """Build a structured TSA token dict with a real RFC 3161 DER blob."""
    tsr_der = _build_real_tsr_der(
        leaf_sk=leaf_sk,
        leaf_cert=leaf_cert,
        bundle_digest_hex=bundle_digest_hex,
        gen_time_iso_z=gen_time,
    )
    subject = signer_subject or leaf_cert.subject.rfc4514_string()
    return {
        "version": 1,
        "policy_oid": "1.3.6.1.4.1.601.10.3.1",
        "message_imprint": {
            "hash_algorithm": "sha256",
            "hashed_message_hex": bundle_digest_hex,
        },
        "serial_number": "424242",
        "gen_time": gen_time,
        "tsa_signature_alg": "ES256",
        "tsa_signer_cert_subject": subject,
        "tsr_der_b64u": _b64u_encode(tsr_der),
    }


def _build_inclusion_proof(
    *,
    claim_digests_hex: list[str],
    bundle_digest_hex: str,
    witness_key: ed25519.Ed25519PrivateKey,
    witness_kid: str = "witness-test-kid-1",
    leaf_index: int = 0,
) -> dict[str, Any]:
    """Build a transparency-log inclusion proof whose witness signature
    verifies against ``witness_key``."""
    synthetic_sibling = hashlib.sha256(b"synthetic-sibling-leaf-1").hexdigest()
    tree_leaves = [bundle_digest_hex, synthetic_sibling]
    tree_root_hex = compute_merkle_root(tree_leaves)
    proof_path = build_inclusion_proof(
        leaf_index=leaf_index,
        claim_digests_hex=tree_leaves,
    )
    sig_bytes = witness_key.sign(tree_root_hex.encode("utf-8"))
    return {
        "log_id": "rekor.test.epochly.com",
        "tree_size": len(tree_leaves),
        "tree_root_hex": tree_root_hex,
        "leaf_index": leaf_index,
        "leaf_digest_hex": bundle_digest_hex,
        "inclusion_proof": proof_path,
        "witness": {
            "alg": "EdDSA",
            "kid": witness_kid,
            "signature_b64u": _b64u_encode(sig_bytes),
        },
    }


def build_bundle(
    *,
    claims: list[dict[str, Any]] | None = None,
    signer_kid: str = "test-signer-kid-1",
    signer_seed: bytes = b"\x01" * 32,
    witness_kid: str = "witness-test-kid-1",
    witness_seed: bytes = b"\x02" * 32,
    decided_at: str = "2026-05-15T12:34:56Z",
    signed_at: str | None = None,
    trust_anchor: str = "https://relay.epochly.com/.well-known/jwks.json",
    include_tsa: bool = True,
    tsa_skew_seconds: int = 0,
    include_log_inclusion: bool = True,
    include_merkle: bool = True,
    subject_id: str | None = "run_01j0test",
    subject_digest_hex: str | None = None,
    key_not_before: str | None = "2026-01-01T00:00:00Z",
    key_not_after: str | None = "2028-01-01T00:00:00Z",
    key_revoked_at: str | None = None,
) -> BuiltBundle:
    """Construct a signed test bundle.

    Returns a :class:`BuiltBundle` holding the bundle dict, a matching
    JWKS, the signing + witness private keys (in memory only), and the
    ephemeral TSA root PEM that tests must pass to the validator via
    ``ValidateBundleOptions(tsa_extra_trusted_roots_pem=...)``.
    """
    if claims is None:
        claims = [
            {
                "claim_id": "claim-1",
                "kind": "command_evidence",
                "command_id": "test-cmd",
                "exit_code": 0,
                "artifact_id": "art-1",
                "evidence_refs": [
                    {
                        "artifact_id": "art-1",
                        "digest": hashlib.sha256(b"artifact-1-bytes").hexdigest(),
                    },
                ],
            },
        ]

    signing_key = make_keypair(signer_seed)
    witness_key = make_keypair(witness_seed)

    signer_jwk = jwk_from_ed25519_public_key(
        signing_key.public_key(), kid=signer_kid,
        not_before=key_not_before, not_after=key_not_after,
    )
    if key_revoked_at is not None:
        signer_jwk["revoked_at"] = key_revoked_at
    witness_jwk = jwk_from_ed25519_public_key(
        witness_key.public_key(), kid=witness_kid,
    )
    jwks: dict[str, Any] = {"keys": [signer_jwk, witness_jwk]}

    if subject_digest_hex is None and subject_id is not None:
        subject_digest_hex = hashlib.sha256(
            subject_id.encode("utf-8")
        ).hexdigest()

    if signed_at is None:
        signed_at = decided_at

    claim_digests = [bundle_digest(c) for c in claims]
    merkle_root_hex = compute_merkle_root(claim_digests) if include_merkle else None

    core_payload: dict[str, Any] = {
        "schema_version": "relay.evidence_bundle.v1",
        "evidence_bundle_id": "bundle-test-1",
        "trust_anchor": trust_anchor,
        "decided_at": decided_at,
        "signed_at": signed_at,
        "claims": claims,
        "subject_id": subject_id,
        "subject_digest_hex": subject_digest_hex,
    }
    if merkle_root_hex is not None:
        core_payload["merkle_root_hex"] = merkle_root_hex

    binding_digest_hex = hashlib.sha256(
        canonical_json_bytes(core_payload)
    ).hexdigest()

    payload = dict(core_payload)

    tsa_root_pem = b""
    if include_tsa:
        leaf_sk, leaf_cert, root_cert = _make_test_tsa_chain()
        tsa_root_pem = root_cert.public_bytes(_serialization.Encoding.PEM)
        gen_time = _shift_iso(decided_at, tsa_skew_seconds)
        payload["tsa_token"] = _build_tsa_token(
            bundle_digest_hex=binding_digest_hex,
            gen_time=gen_time,
            leaf_sk=leaf_sk,
            leaf_cert=leaf_cert,
        )

    if include_log_inclusion:
        payload["log_inclusion_proof"] = _build_inclusion_proof(
            claim_digests_hex=claim_digests,
            bundle_digest_hex=binding_digest_hex,
            witness_key=witness_key,
            witness_kid=witness_kid,
        )

    sig_record = sign_payload_ed25519(payload, signing_key, kid=signer_kid)
    payload_digest_hex = binding_digest_hex
    bundle = dict(payload)
    bundle["signatures"] = [sig_record]
    return BuiltBundle(
        bundle=bundle,
        jwks=jwks,
        signing_key=signing_key,
        witness_key=witness_key,
        bundle_digest_hex=payload_digest_hex,
        tsa_extra_roots_pem=tsa_root_pem,
    )


def _shift_iso(iso_z: str, delta_seconds: int) -> str:
    """Return ``iso_z`` shifted by ``delta_seconds``. Preserves the Z suffix."""
    dt = _dt.datetime.fromisoformat(iso_z[:-1] + "+00:00")
    dt2 = dt + _dt.timedelta(seconds=delta_seconds)
    return dt2.astimezone(_dt.UTC).isoformat().replace("+00:00", "Z")
