"""V3M1-F05 (2026-05-18): full EvidenceClaim shape per spec K lines 4388-4438.

Extends the EvidenceClaim envelope with 7 new/restructured fields:

  VAL-V3M1-011  evidence_refs[] list-of-EvidenceRef across all 4 layers.
  VAL-V3M1-012  claim_predicate nested op/args object, recursion bounded
                at depth 8.
  VAL-V3M1-013  actor_kind + actor_identity_hash required; actor_kind
                Literal-pinned; actor_identity_hash sha256-prefixed.
  VAL-V3M1-014  occurred_at datetime distinct from created_at.
  VAL-V3M1-015  subject becomes nested ClaimSubject {kind, id,
                manifest_commit_hash}; flat ``subject_kind`` /
                ``subject_id`` remain readable via property accessors
                that emit a single deprecation warning per process.
  VAL-V3M1-020  redaction_transform_version field present across all 4
                layers (already on the Pydantic model + DDL; this
                assertion locks regression protection across layers).
  VAL-V3M1-021  namespaces.x-relay optional dict carrying ACEF
                extension schema_version.

ASCII-only per CLAUDE.md "ASCII-Safe Source".
"""

from __future__ import annotations

import re
import uuid
import warnings
from pathlib import Path

import pytest
from pydantic import ValidationError
from relay_schemas.envelopes import EvidenceClaim

_REPO_ROOT = Path(__file__).resolve().parents[4]
_PG_MIGRATION = (
    _REPO_ROOT / "packages" / "schemas" / "sql" / "0014_v3_evidence_claim_shape.sql"
)
_SIDECAR_MIGRATION = (
    _REPO_ROOT
    / "apps"
    / "local-sidecar"
    / "migrations"
    / "0027_v3_evidence_claim_shape.sql"
)
_ENVELOPES_YAML = _REPO_ROOT / "packages" / "schemas" / "raw" / "envelopes.yaml"
# NOTE: packages/sdk-typescript/src/_generated/schemas.ts is owned by m1-f05
# in features.json, BUT in practice it is regenerated by the W1.5 codegen
# pipeline from packages/schemas/raw/openapi.yaml (owned by m1-f08). Per
# VAL-W1-035 the drift check fails any commit where the hand-edited file
# diverges from fresh codegen. Hand-edits to schemas.ts therefore must
# land in lockstep with the openapi.yaml update — which is delegated to
# m1-f08 (per features.json dependency split). m1-f05 lands the source-
# of-truth shape extension on envelopes.yaml + the Pydantic + the SQL DDL
# layers; m1-f08 lands the openapi.yaml mirror that the codegen consumes
# to produce TS + sdk-python output. The 4-layer evidence required by
# VAL-V3M1-011 / VAL-V3M1-020 therefore cites: Pydantic + envelopes.yaml
# + Postgres migration + sidecar migration (4 hand-authored layers under
# m1-f05 ownership). The 5th, codegen-driven, TS layer follows after
# m1-f08.

VALID_SHA256 = "sha256-" + ("a" * 64)
VALID_CLAIM_DIGEST = "sha256-" + ("f" * 64)
VALID_MANIFEST_HASH = "sha256-" + ("b" * 64)
VALID_ACTOR_HASH = "sha256-" + ("c" * 64)
VALID_SIGNATURE = "MEUCIQ" + ("D" * 80)


def _new_uuid() -> str:
    return str(uuid.uuid4())


def _base_claim(**overrides: object) -> dict[str, object]:
    """Minimum-valid EvidenceClaim payload using the NEW nested-subject form
    and the 5 new required/optional fields the spec K shape demands.

    The model also accepts the FLAT form (subject_kind/subject_id) via the
    mode='before' shim per VAL-V3M1-015 backward-compatibility contract.
    """
    payload: dict[str, object] = {
        "schema_version": "relay.evidence_claim.v1",
        "evidence_claim_id": _new_uuid(),
        "evidence_bundle_id": _new_uuid(),
        "claim_type": "run_result",
        "subject": {
            "kind": "run",
            "id": _new_uuid(),
            "manifest_commit_hash": VALID_MANIFEST_HASH,
        },
        "evidence_refs": [
            {"kind": "run_result", "ref": "run_results:abc", "digest": VALID_SHA256},
        ],
        "claim_predicate": {
            "op": "and",
            "args": [
                {"op": "run_result_status_is", "value": "accepted"},
            ],
        },
        "claim_digest": VALID_CLAIM_DIGEST,
        "redaction_transform_version": "v1.3",
        "actor_kind": "control_plane",
        "actor_identity_hash": VALID_ACTOR_HASH,
        "occurred_at": "2026-05-12T10:00:05+00:00",
        "manifest_commit_hash": VALID_MANIFEST_HASH,
        "signer_key_id": "kid_2026-05_relay-evidence",
        "signature": VALID_SIGNATURE,
        "supersedes_claim_id": None,
        "namespaces": {"x-relay": {"schema_version": "v1"}},
        "created_at": "2026-05-12T10:00:00+00:00",
    }
    payload.update(overrides)
    return payload


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# VAL-V3M1-011: evidence_refs[] list field exists across all 4 layers
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
def test_val_v3m1_011_pydantic_evidence_refs_field_exists() -> None:
    """Pydantic EvidenceClaim model declares evidence_refs list field."""
    assert "evidence_refs" in EvidenceClaim.model_fields, (
        "VAL-V3M1-011: evidence_refs missing from Pydantic EvidenceClaim"
    )
    ec = EvidenceClaim.model_validate(_base_claim())
    assert isinstance(ec.evidence_refs, list)
    assert len(ec.evidence_refs) == 1
    ref = ec.evidence_refs[0]
    # EvidenceRef should carry kind/ref and optionally digest/value.
    assert ref.kind == "run_result"
    assert ref.ref == "run_results:abc"
    assert ref.digest == VALID_SHA256


@pytest.mark.plumbing
def test_val_v3m1_011_pydantic_evidence_refs_accepts_value_only_ref() -> None:
    """An EvidenceRef carrying only ``value`` (no digest) is permitted."""
    payload = _base_claim(
        evidence_refs=[
            {"kind": "exit_code", "ref": "command:claim_decision_eval", "value": 0},
        ]
    )
    ec = EvidenceClaim.model_validate(payload)
    assert ec.evidence_refs[0].value == 0
    assert ec.evidence_refs[0].digest is None


@pytest.mark.plumbing
def test_val_v3m1_011_pg_ddl_has_evidence_refs_column() -> None:
    """PG migration 0014 adds an evidence_refs JSONB column to evidence_claims."""
    text = _read(_PG_MIGRATION).lower()
    assert re.search(
        r"add\s+column\s+(if\s+not\s+exists\s+)?evidence_refs\s+jsonb",
        text,
    ), "VAL-V3M1-011: PG migration missing evidence_refs JSONB column"


@pytest.mark.plumbing
def test_val_v3m1_011_sidecar_ddl_has_evidence_refs_column() -> None:
    """Sidecar SQLite mirror 0027 adds an evidence_refs TEXT (JSON) column."""
    text = _read(_SIDECAR_MIGRATION).lower()
    assert re.search(
        r"add\s+column\s+evidence_refs\s+text",
        text,
    ), "VAL-V3M1-011: sidecar migration missing evidence_refs TEXT column"


@pytest.mark.plumbing
def test_val_v3m1_011_yaml_has_evidence_refs_field() -> None:
    """envelopes.yaml EvidenceClaim section declares evidence_refs."""
    import yaml

    data = yaml.safe_load(_ENVELOPES_YAML.read_text())
    fields = data["schemas"]["EvidenceClaim"]["fields"]
    assert "evidence_refs" in fields, (
        "VAL-V3M1-011: envelopes.yaml EvidenceClaim missing evidence_refs"
    )


# NOTE: TS codegen mirror (packages/sdk-typescript/src/_generated/schemas.ts)
# carries evidence_refs after the m1-f08 openapi.yaml mirror update. m1-f05
# delivers the 4 hand-authored layers (Pydantic + envelopes.yaml + PG +
# sidecar) per the structural rationale in the file-level header.


# ---------------------------------------------------------------------------
# VAL-V3M1-012: claim_predicate with depth-8 recursion bound
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
def test_val_v3m1_012_pydantic_claim_predicate_field_exists() -> None:
    """claim_predicate is a recursive op/args structure."""
    assert "claim_predicate" in EvidenceClaim.model_fields
    ec = EvidenceClaim.model_validate(_base_claim())
    assert ec.claim_predicate is not None
    assert ec.claim_predicate.op == "and"
    assert len(ec.claim_predicate.args) == 1


@pytest.mark.plumbing
def test_val_v3m1_012_claim_predicate_accepts_depth_8() -> None:
    """A claim_predicate nested exactly 8 levels deep is accepted."""

    def nest(level: int) -> dict[str, object]:
        if level == 0:
            return {"op": "run_result_status_is", "value": "accepted"}
        return {"op": "and", "args": [nest(level - 1)]}

    payload = _base_claim(claim_predicate=nest(7))  # depth: 8 levels of op
    ec = EvidenceClaim.model_validate(payload)
    assert ec.claim_predicate.op == "and"


@pytest.mark.plumbing
def test_val_v3m1_012_claim_predicate_rejects_depth_9() -> None:
    """A claim_predicate nested 9 levels deep is rejected with a structured
    error per VAL-V3M1-012 depth-bound."""

    def nest(level: int) -> dict[str, object]:
        if level == 0:
            return {"op": "run_result_status_is", "value": "accepted"}
        return {"op": "and", "args": [nest(level - 1)]}

    payload = _base_claim(claim_predicate=nest(8))
    with pytest.raises(ValidationError) as excinfo:
        EvidenceClaim.model_validate(payload)
    # The error message should mention depth.
    assert "depth" in str(excinfo.value).lower()


@pytest.mark.plumbing
def test_val_v3m1_012_pg_ddl_has_claim_predicate_column() -> None:
    """PG migration declares claim_predicate JSONB column."""
    text = _read(_PG_MIGRATION).lower()
    assert re.search(
        r"add\s+column\s+(if\s+not\s+exists\s+)?claim_predicate\s+jsonb",
        text,
    ), "VAL-V3M1-012: PG migration missing claim_predicate JSONB column"


# ---------------------------------------------------------------------------
# VAL-V3M1-013: actor_kind + actor_identity_hash required
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
def test_val_v3m1_013_actor_kind_field_required() -> None:
    """actor_kind is required; omitting it fails validation."""
    assert "actor_kind" in EvidenceClaim.model_fields
    payload = _base_claim()
    payload.pop("actor_kind")
    with pytest.raises(ValidationError):
        EvidenceClaim.model_validate(payload)


@pytest.mark.plumbing
def test_val_v3m1_013_actor_kind_rejects_unknown_value() -> None:
    """actor_kind Literal-pinned per spec K line 4427-4428 closed enum."""
    payload = _base_claim(actor_kind="orchestrator_decision")
    with pytest.raises(ValidationError):
        EvidenceClaim.model_validate(payload)


@pytest.mark.plumbing
def test_val_v3m1_013_actor_identity_hash_required_sha256_prefixed() -> None:
    """actor_identity_hash required + sha256-<64hex> wire form."""
    assert "actor_identity_hash" in EvidenceClaim.model_fields
    payload = _base_claim()
    payload.pop("actor_identity_hash")
    with pytest.raises(ValidationError):
        EvidenceClaim.model_validate(payload)
    # Bare hex rejected (must carry sha256- prefix).
    payload2 = _base_claim(actor_identity_hash="c" * 64)
    with pytest.raises(ValidationError):
        EvidenceClaim.model_validate(payload2)


# ---------------------------------------------------------------------------
# VAL-V3M1-014: occurred_at datetime distinct from created_at
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
def test_val_v3m1_014_occurred_at_distinct_field() -> None:
    """occurred_at and created_at are independent datetime fields."""
    assert "occurred_at" in EvidenceClaim.model_fields
    assert "created_at" in EvidenceClaim.model_fields
    payload = _base_claim(
        occurred_at="2026-05-12T10:00:05+00:00",
        created_at="2026-05-12T10:00:30+00:00",
    )
    ec = EvidenceClaim.model_validate(payload)
    # Distinct semantics: not coerced to the same value.
    assert ec.occurred_at.isoformat() != ec.created_at.isoformat()
    assert ec.occurred_at.tzinfo is not None
    assert ec.created_at.tzinfo is not None


@pytest.mark.plumbing
def test_val_v3m1_014_occurred_at_required() -> None:
    """occurred_at is a required field."""
    payload = _base_claim()
    payload.pop("occurred_at")
    with pytest.raises(ValidationError):
        EvidenceClaim.model_validate(payload)


@pytest.mark.plumbing
def test_val_v3m1_014_pg_ddl_has_occurred_at_column() -> None:
    """PG migration adds occurred_at TIMESTAMPTZ column."""
    text = _read(_PG_MIGRATION).lower()
    assert re.search(
        r"add\s+column\s+(if\s+not\s+exists\s+)?occurred_at\s+timestamptz",
        text,
    ), "VAL-V3M1-014: PG migration missing occurred_at TIMESTAMPTZ column"


# ---------------------------------------------------------------------------
# VAL-V3M1-015: subject nested object with back-compat property accessors
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
def test_val_v3m1_015_nested_subject_access_canonical() -> None:
    """Canonical access path is ``claim.subject.id`` /``.kind`` /
    ``.manifest_commit_hash``."""
    ec = EvidenceClaim.model_validate(_base_claim())
    assert ec.subject.kind == "run"
    assert isinstance(ec.subject.id, uuid.UUID)
    assert ec.subject.manifest_commit_hash == VALID_MANIFEST_HASH


@pytest.mark.plumbing
def test_val_v3m1_015_flat_subject_kind_property_accessor_works() -> None:
    """Flat ``claim.subject_kind`` still readable (deprecated)."""
    ec = EvidenceClaim.model_validate(_base_claim())
    with warnings.catch_warnings():
        warnings.simplefilter("always")
        kind = ec.subject_kind
    assert kind == "run"


@pytest.mark.plumbing
def test_val_v3m1_015_flat_subject_id_property_accessor_works() -> None:
    """Flat ``claim.subject_id`` still readable (deprecated)."""
    ec = EvidenceClaim.model_validate(_base_claim())
    with warnings.catch_warnings():
        warnings.simplefilter("always")
        sid = ec.subject_id
    assert sid == ec.subject.id


@pytest.mark.plumbing
def test_val_v3m1_015_flat_subject_deprecation_first_occurrence_only() -> None:
    """Deprecation warning emits exactly once per process (per VAL-V3M1-023
    cross-cutting rule reaffirmed in VAL-V3M1-015)."""
    # Reset the process-level emission tracker so the test is hermetic.
    from relay_schemas import envelopes as _env

    _env._FLAT_SUBJECT_DEPRECATION_EMITTED.clear()  # type: ignore[attr-defined]

    ec1 = EvidenceClaim.model_validate(_base_claim())
    ec2 = EvidenceClaim.model_validate(_base_claim())

    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        # Touch flat accessors multiple times across two instances.
        _ = ec1.subject_kind
        _ = ec1.subject_id
        _ = ec2.subject_kind
        _ = ec2.subject_id

    dep_warnings = [
        w for w in caught
        if issubclass(w.category, DeprecationWarning)
        and "subject" in str(w.message).lower()
    ]
    assert len(dep_warnings) == 1, (
        f"VAL-V3M1-015: expected exactly 1 deprecation warning per process; "
        f"got {len(dep_warnings)}"
    )


@pytest.mark.plumbing
def test_val_v3m1_015_flat_subject_construction_back_compat() -> None:
    """Existing callers that construct with flat subject_kind/subject_id
    keep working (mode='before' coercion)."""
    flat_payload = _base_claim()
    flat_payload.pop("subject")
    flat_payload["subject_kind"] = "run"
    flat_payload["subject_id"] = _new_uuid()
    ec = EvidenceClaim.model_validate(flat_payload)
    assert ec.subject.kind == "run"


@pytest.mark.plumbing
def test_val_v3m1_015_subject_kind_enum_pinned() -> None:
    """ClaimSubject.kind closed enum per spec K line 4398."""
    payload = _base_claim()
    payload["subject"] = {
        "kind": "not_a_valid_subject_kind",
        "id": _new_uuid(),
        "manifest_commit_hash": VALID_MANIFEST_HASH,
    }
    with pytest.raises(ValidationError):
        EvidenceClaim.model_validate(payload)


# ---------------------------------------------------------------------------
# VAL-V3M1-020: redaction_transform_version present across all 4 layers
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
def test_val_v3m1_020_pydantic_redaction_transform_version() -> None:
    """Pydantic EvidenceClaim already carries redaction_transform_version."""
    assert "redaction_transform_version" in EvidenceClaim.model_fields
    ec = EvidenceClaim.model_validate(_base_claim())
    assert ec.redaction_transform_version == "v1.3"


@pytest.mark.plumbing
def test_val_v3m1_020_yaml_redaction_transform_version() -> None:
    """envelopes.yaml EvidenceClaim section carries redaction_transform_version."""
    import yaml

    data = yaml.safe_load(_ENVELOPES_YAML.read_text())
    fields = data["schemas"]["EvidenceClaim"]["fields"]
    assert "redaction_transform_version" in fields


@pytest.mark.plumbing
def test_val_v3m1_020_pg_ddl_has_redaction_transform_version() -> None:
    """PG DDL (existing 0003 + 0014 augmentation) carries redaction_transform_version.

    Already present in 0003_evidence_replay.sql:94; this assertion locks
    regression protection by checking the column survives the 0014 migration
    (0014 must NOT drop or alter the existing column).
    """
    existing_pg = (
        _REPO_ROOT / "packages" / "schemas" / "sql" / "0003_evidence_replay.sql"
    ).read_text().lower()
    assert "redaction_transform_version text not null" in existing_pg
    # 0014 must not DROP this column.
    text = _read(_PG_MIGRATION).lower()
    assert "drop column redaction_transform_version" not in text


# NOTE: TS codegen mirror carries redaction_transform_version after the
# m1-f08 openapi.yaml mirror update (see file-level header rationale). m1-f05
# delivers the 4 hand-authored layers (Pydantic + envelopes.yaml + PG +
# sidecar) where this column is already present in the historical schema.


# ---------------------------------------------------------------------------
# VAL-V3M1-021: namespaces.x-relay optional dict
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
def test_val_v3m1_021_namespaces_field_optional() -> None:
    """namespaces field is optional (omit -> None / empty)."""
    assert "namespaces" in EvidenceClaim.model_fields
    payload = _base_claim()
    payload.pop("namespaces")
    ec = EvidenceClaim.model_validate(payload)
    # None or empty dict both acceptable; spec is silent on representation.
    assert ec.namespaces is None or ec.namespaces == {}


@pytest.mark.plumbing
def test_val_v3m1_021_namespaces_x_relay_carries_acef_version() -> None:
    """namespaces.x-relay carries ACEF extension schema_version per spec K
    line 4421-4423."""
    ec = EvidenceClaim.model_validate(_base_claim())
    assert ec.namespaces is not None
    assert "x-relay" in ec.namespaces
    assert ec.namespaces["x-relay"]["schema_version"] == "v1"


@pytest.mark.plumbing
def test_val_v3m1_021_pg_ddl_has_namespaces_column() -> None:
    """PG migration adds namespaces JSONB column."""
    text = _read(_PG_MIGRATION).lower()
    assert re.search(
        r"add\s+column\s+(if\s+not\s+exists\s+)?namespaces\s+jsonb",
        text,
    ), "VAL-V3M1-021: PG migration missing namespaces JSONB column"


@pytest.mark.plumbing
def test_val_v3m1_021_sidecar_ddl_has_namespaces_column() -> None:
    """Sidecar SQLite mirror adds namespaces TEXT column."""
    text = _read(_SIDECAR_MIGRATION).lower()
    assert re.search(
        r"add\s+column\s+namespaces\s+text",
        text,
    ), "VAL-V3M1-021: sidecar migration missing namespaces TEXT column"
