"""W17.1 RFC 8785 IETF conformance corpus tests.

Pinned-vector conformance suite that exercises the Python verifier's
JCS encoder against the IETF datatracker text of RFC 8785. The corpus
file ``tests/conformance/jcs/rfc8785_ietf_corpus.json`` and the
upstream-pins file ``tests/conformance/jcs/.upstream-pins.json`` are
generated by ``scripts/generate-jcs-rfc8785-ietf-corpus.py``. The
sibling vitest mirror at
``packages/verifier-typescript/test/w17_1_ietf_corpus.test.ts`` loads
the same files and asserts byte-identical output from the TS encoder
(VAL-W17-002 cross-runtime parity).

Assertion coverage:

  * VAL-W17-001: corpus sourced from IETF datatracker, pinned by SHA-256
    (asserted by ``test_corpus_pinned_to_ietf_datatracker``).
  * VAL-W17-002: 100% pass on cel-python JCS AND TS SDK JCS paths
    (Python half asserted here; TS half asserted in the vitest mirror).
  * VAL-W17-003: UTF-8 NFC normalization enforced before hashing
    (asserted by the NFC vector group + an explicit
    ``test_nfc_normalization_enforced`` check).
  * VAL-W17-004: number-serialization edge cases pass (RFC 8785 sec
    3.2.2.3) (asserted by the num_edge vector group + boundary checks).
  * VAL-W17-005: object-key sort order is RFC 8785 sec 3.2.3
    (asserted by the sort_utf16 vector group + adjacency checks).
  * VAL-W17-022: failures emit per-vector full diff (asserted by the
    ``_format_diff`` helper invoked on any mismatch).

ASCII-only per CLAUDE.md "ASCII-Safe Source".
"""

from __future__ import annotations

import base64
import hashlib
import json
import re
import unicodedata
from pathlib import Path
from typing import Any

import pytest
from relay_verifier.canonical import (
    JCSEncodeError,
    jcs_canonicalize,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
CORPUS_PATH = REPO_ROOT / "conformance" / "jcs" / "rfc8785_ietf_corpus.json"
PINS_PATH = REPO_ROOT / "conformance" / "jcs" / ".upstream-pins.json"

SCHEMA_ID = "relay.conformance.jcs.ietf.v1"
MIN_APPENDIX_B_CASES = 15
MIN_NFC_CASES = 10
MIN_NUM_EDGE_CASES = 10
MIN_SORT_UTF16_CASES = 6

_HEX_64 = re.compile(r"^[0-9a-f]{64}$")
_IETF_DATATRACKER_URL = "https://datatracker.ietf.org/doc/html/rfc8785"


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------


def _load_corpus() -> dict[str, Any]:
    if not CORPUS_PATH.is_file():
        raise AssertionError(
            f"W17.1 corpus missing at {CORPUS_PATH}; "
            "regenerate via scripts/generate-jcs-rfc8785-ietf-corpus.py."
        )
    return json.loads(CORPUS_PATH.read_text(encoding="utf-8"))


def _load_pins() -> dict[str, Any]:
    if not PINS_PATH.is_file():
        raise AssertionError(
            f"W17.1 pins missing at {PINS_PATH}; "
            "regenerate via scripts/generate-jcs-rfc8785-ietf-corpus.py."
        )
    return json.loads(PINS_PATH.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Per-vector diff formatter (VAL-W17-022)
# ---------------------------------------------------------------------------


def _format_diff(
    case_name: str,
    case_category: str,
    expected_bytes: bytes,
    actual_bytes: bytes,
) -> str:
    """Format a per-vector full diff suitable for the pytest failure
    summary. Mandated by VAL-W17-022: any byte mismatch MUST be
    reported with the full expected vs actual bytes (hex), the
    decoded UTF-8 strings (with non-printable chars escaped), and
    the per-byte index of the first diverging byte. No count-only
    summary is acceptable.
    """
    min_len = min(len(expected_bytes), len(actual_bytes))
    first_diff_idx = -1
    for i in range(min_len):
        if expected_bytes[i] != actual_bytes[i]:
            first_diff_idx = i
            break
    if first_diff_idx == -1 and len(expected_bytes) != len(actual_bytes):
        first_diff_idx = min_len
    lines = [
        "VAL-W17-022 per-vector diff:",
        f"  case_name      = {case_name!r}",
        f"  category       = {case_category!r}",
        f"  expected_bytes = {expected_bytes!r}",
        f"  actual_bytes   = {actual_bytes!r}",
        f"  expected_hex   = {expected_bytes.hex()}",
        f"  actual_hex     = {actual_bytes.hex()}",
        f"  expected_len   = {len(expected_bytes)}",
        f"  actual_len     = {len(actual_bytes)}",
        f"  first_diff_idx = {first_diff_idx}",
    ]
    if first_diff_idx >= 0:
        e = expected_bytes[first_diff_idx] if first_diff_idx < len(expected_bytes) else None
        a = actual_bytes[first_diff_idx] if first_diff_idx < len(actual_bytes) else None
        lines.append(
            f"  first_diff_exp_byte = {e!r} actual_byte = {a!r}"
        )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Schema + coverage shape (sanity checks before assertion-specific tests)
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-001")
def test_corpus_schema_and_minimum_coverage() -> None:
    """The corpus declares the v1 schema and reaches per-category
    minimum case counts so the conformance breadth claim is real."""
    corpus = _load_corpus()
    assert corpus["schema"] == SCHEMA_ID, (
        f"VAL-W17-001 schema mismatch: expected {SCHEMA_ID!r}, "
        f"got {corpus.get('schema')!r}"
    )
    counts = corpus["case_counts"]
    assert counts["appendix_b"] >= MIN_APPENDIX_B_CASES, (
        f"VAL-W17-001 too few Appendix B cases: {counts['appendix_b']}"
    )
    assert counts["nfc"] >= MIN_NFC_CASES, (
        f"VAL-W17-003 too few NFC cases: {counts['nfc']}"
    )
    assert counts["num_edge"] >= MIN_NUM_EDGE_CASES, (
        f"VAL-W17-004 too few num_edge cases: {counts['num_edge']}"
    )
    assert counts["sort_utf16"] >= MIN_SORT_UTF16_CASES, (
        f"VAL-W17-005 too few sort_utf16 cases: {counts['sort_utf16']}"
    )


# ---------------------------------------------------------------------------
# VAL-W17-001: IETF datatracker pin
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-001")
def test_corpus_pinned_to_ietf_datatracker() -> None:
    """The corpus + pins file together pin the corpus to the IETF
    datatracker text of RFC 8785 by SHA-256 over an inline transcript
    of the normative paragraphs we depend on."""
    pins = _load_pins()
    assert pins["source_url"] == _IETF_DATATRACKER_URL, (
        f"VAL-W17-001 source URL not pinned to IETF datatracker: "
        f"got {pins.get('source_url')!r}"
    )
    assert pins["rfc"] == "RFC 8785"
    assert _HEX_64.match(pins["transcript_sha256"]), (
        f"VAL-W17-001 transcript_sha256 not 64-char hex: "
        f"{pins.get('transcript_sha256')!r}"
    )
    # The corpus file references the same source.
    corpus = _load_corpus()
    assert corpus["source"]["url"] == _IETF_DATATRACKER_URL


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-001")
def test_pins_transcript_sha256_matches_recorded_length() -> None:
    """The transcript byte length recorded in pins is a non-negative
    integer matching the SHA-256-computed transcript. Sanity check
    against partial-truncation tampering."""
    pins = _load_pins()
    assert isinstance(pins["transcript_byte_length"], int)
    assert pins["transcript_byte_length"] > 0


# ---------------------------------------------------------------------------
# VAL-W17-002: 100% pass on cel-python JCS path (Python half)
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-002")
def test_every_vector_canonicalizes_byte_for_byte_python() -> None:
    """Every value-kind case canonicalizes to the corpus-pinned bytes
    via the verifier's JCS encoder. ANY single failure fails the
    suite. Per VAL-W17-022, the per-vector diff is emitted on
    failure (no count-only summary)."""
    corpus = _load_corpus()
    failures: list[str] = []
    pass_count = 0
    for case in corpus["cases"]:
        if case.get("kind") != "value":
            continue
        actual = jcs_canonicalize(case["input"])
        expected = base64.b64decode(case["expected_canonical_b64"])
        if actual != expected:
            failures.append(
                _format_diff(case["name"], case.get("category", ""), expected, actual)
            )
            continue
        # Defence in depth: the corpus's UTF-8 string mirror MUST
        # match the bytes when re-encoded.
        utf8_mirror = case["expected_canonical_utf8"].encode("utf-8")
        if actual != utf8_mirror:
            failures.append(
                _format_diff(
                    case["name"] + " (utf8 mirror)",
                    case.get("category", ""),
                    utf8_mirror,
                    actual,
                )
            )
            continue
        pass_count += 1
    assert not failures, (
        f"VAL-W17-002: {len(failures)} vector(s) failed Python parity:\n\n"
        + "\n\n".join(failures)
    )
    # Aggregate explicit count assertion for evidence-bundle pairing.
    expected_total = sum(1 for c in corpus["cases"] if c.get("kind") == "value")
    assert pass_count == expected_total, (
        f"VAL-W17-002: python_pass={pass_count} expected_total={expected_total}"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-002")
def test_corpus_sha256_digests_match_python_runtime() -> None:
    """The SHA-256 over the canonical bytes equals the corpus golden
    digest for every case. Drift across Python 3.12 / 3.13 / 3.14 of
    repr(float) byte form would fail here."""
    corpus = _load_corpus()
    failures: list[str] = []
    for case in corpus["cases"]:
        if case.get("kind") != "value":
            continue
        actual_digest = hashlib.sha256(jcs_canonicalize(case["input"])).hexdigest()
        if actual_digest != case["expected_sha256"]:
            failures.append(
                f"{case['name']}: expected={case['expected_sha256']!r} "
                f"actual={actual_digest!r}"
            )
    assert not failures, (
        f"VAL-W17-002: SHA-256 drift on {len(failures)} case(s):\n  "
        + "\n  ".join(failures)
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-002")
def test_every_sha256_digest_is_lowercase_hex_64() -> None:
    """Each corpus case's expected_sha256 is lowercase 64-char hex --
    catches a regenerator that emitted uppercase or short hex."""
    corpus = _load_corpus()
    for case in corpus["cases"]:
        if case.get("kind") != "value":
            continue
        digest = case["expected_sha256"]
        assert _HEX_64.match(digest), (
            f"VAL-W17-002: case {case['name']} digest not 64-char hex: "
            f"{digest!r}"
        )


# ---------------------------------------------------------------------------
# VAL-W17-003: UTF-8 NFC normalization
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-003")
def test_nfc_vector_count_meets_floor() -> None:
    """At least 10 NFC vectors per the assertion text."""
    corpus = _load_corpus()
    nfc_cases = [c for c in corpus["cases"] if c.get("category") == "nfc"]
    assert len(nfc_cases) >= MIN_NFC_CASES, (
        f"VAL-W17-003 requires >= {MIN_NFC_CASES} NFC vectors; "
        f"got {len(nfc_cases)}"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-003")
def test_nfc_normalization_enforced_on_string_value() -> None:
    """A decomposed input MUST canonicalize to the same bytes as its
    NFC-equivalent form. Direct assertion against the encoder."""
    decomposed = "é"  # 'e' + COMBINING ACUTE ACCENT
    precomposed = "é"   # 'e' acute (NFC)
    out_d = jcs_canonicalize(decomposed)
    out_p = jcs_canonicalize(precomposed)
    assert out_d == out_p, (
        f"VAL-W17-003: encoder must apply NFC to string values; "
        f"decomposed={out_d!r} precomposed={out_p!r}"
    )
    # And the canonical bytes equal the NFC form's JSON encoding.
    assert out_d == b'"\xc3\xa9"', (
        f"VAL-W17-003: canonical bytes must encode NFC form 'e' acute "
        f"(U+00E9 -> UTF-8 0xC3 0xA9); got {out_d!r}"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-003")
def test_nfc_normalization_enforced_on_object_key() -> None:
    """A decomposed object KEY MUST canonicalize identically to its
    NFC-equivalent. Catches regressions where NFC is applied to
    string values but not to keys."""
    out_d = jcs_canonicalize({"é": 1})
    out_p = jcs_canonicalize({"é": 1})
    assert out_d == out_p, (
        f"VAL-W17-003: encoder must apply NFC to object keys; "
        f"decomposed_key={out_d!r} precomposed_key={out_p!r}"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-003")
def test_canonical_output_is_nfc_idempotent() -> None:
    """The canonical bytes' UTF-8 decoding MUST equal its own NFC
    form. The encoder ensures this by normalizing before serialization;
    a regression would produce non-NFC bytes for non-NFC inputs."""
    corpus = _load_corpus()
    failures: list[str] = []
    for case in corpus["cases"]:
        if case.get("kind") != "value":
            continue
        text = jcs_canonicalize(case["input"]).decode("utf-8")
        if unicodedata.normalize("NFC", text) != text:
            failures.append(
                f"{case['name']}: canonical output is NOT NFC-idempotent"
            )
    assert not failures, (
        "VAL-W17-003: " + "; ".join(failures)
    )


# ---------------------------------------------------------------------------
# VAL-W17-004: numeric edge cases
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-004")
def test_num_edge_vector_count_meets_floor() -> None:
    """At least 10 num_edge vectors covering RFC 8785 sec 3.2.2.3."""
    corpus = _load_corpus()
    num_cases = [c for c in corpus["cases"] if c.get("category") == "num_edge"]
    assert len(num_cases) >= MIN_NUM_EDGE_CASES, (
        f"VAL-W17-004 requires >= {MIN_NUM_EDGE_CASES} num_edge vectors; "
        f"got {len(num_cases)}"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-004")
def test_negative_zero_collapses_to_unsigned_zero() -> None:
    """RFC 8785 sec 3.2.2.3 -- IEEE-754 -0 emits as '0'."""
    assert jcs_canonicalize(-0.0) == b"0"
    assert jcs_canonicalize(0.0) == b"0"
    assert jcs_canonicalize(0) == b"0"


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-004")
def test_exponent_boundary_1e_minus_6() -> None:
    """At the 1e-6 lower-exponent boundary, ECMA-262 emits decimal
    form; just below, it switches to exponential."""
    assert jcs_canonicalize(1e-6) == b"0.000001"
    assert jcs_canonicalize(9.999999e-7) == b"9.999999e-7"
    assert jcs_canonicalize(1e-7) == b"1e-7"


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-004")
def test_exponent_boundary_1e21() -> None:
    """At the 1e21 upper-exponent boundary, ECMA-262 emits exponential;
    just below, it emits decimal form."""
    assert jcs_canonicalize(1e21) == b"1e+21"
    assert jcs_canonicalize(1e20) == b"100000000000000000000"


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-004")
def test_max_safe_integer_boundaries() -> None:
    """Number.MAX_SAFE_INTEGER and its negation emit as plain decimal."""
    assert jcs_canonicalize(9007199254740991) == b"9007199254740991"
    assert jcs_canonicalize(-9007199254740991) == b"-9007199254740991"


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-004")
def test_subnormal_double_emits_exponential() -> None:
    """Smallest positive subnormal double 5e-324 emits in exponential
    form via the ECMA-262 ToString algorithm."""
    assert jcs_canonicalize(5e-324) == b"5e-324"


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-004")
def test_max_finite_double_emits_exponential() -> None:
    """Largest finite double 1.7976931348623157e308 emits in
    exponential form via the ECMA-262 ToString algorithm."""
    assert jcs_canonicalize(1.7976931348623157e308) == (
        b"1.7976931348623157e+308"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-004")
def test_nan_inf_rejected() -> None:
    """RFC 8785 forbids NaN, +Inf, -Inf at canonicalization time."""
    with pytest.raises(JCSEncodeError):
        jcs_canonicalize(float("nan"))
    with pytest.raises(JCSEncodeError):
        jcs_canonicalize(float("inf"))
    with pytest.raises(JCSEncodeError):
        jcs_canonicalize(float("-inf"))


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-004")
def test_corpus_reject_cases_enumerate_non_finite() -> None:
    corpus = _load_corpus()
    reject_names = {c["name"] for c in corpus["reject_cases"]}
    assert "reject-nan" in reject_names
    assert "reject-positive-infinity" in reject_names
    assert "reject-negative-infinity" in reject_names


# ---------------------------------------------------------------------------
# VAL-W17-005: object-key sort order (UTF-16 code-unit lex)
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-005")
def test_sort_utf16_vector_count_meets_floor() -> None:
    corpus = _load_corpus()
    sort_cases = [
        c for c in corpus["cases"] if c.get("category") == "sort_utf16"
    ]
    assert len(sort_cases) >= MIN_SORT_UTF16_CASES, (
        f"VAL-W17-005 requires >= {MIN_SORT_UTF16_CASES} sort_utf16 vectors; "
        f"got {len(sort_cases)}"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-005")
def test_uppercase_precedes_lowercase_by_code_unit() -> None:
    """ASCII A(0x41) < B(0x42) < a(0x61) < b(0x62)."""
    out = jcs_canonicalize({"b": 1, "B": 2, "a": 3, "A": 4})
    assert out == b'{"A":4,"B":2,"a":3,"b":1}'


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-005")
def test_cross_script_bmp_sort_order() -> None:
    """U+0041 (Latin A) < U+0391 (Greek Alpha) < U+0410 (Cyrillic A)."""
    out = jcs_canonicalize({"A": "ascii", "А": "cyr", "Α": "greek"})
    expected = '{"A":"ascii","Α":"greek","А":"cyr"}'.encode()
    assert out == expected


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-005")
def test_empty_key_sorts_first() -> None:
    """Empty string key sorts before all non-empty keys."""
    out = jcs_canonicalize({"a": 1, "": 2, "b": 3})
    assert out == b'{"":2,"a":1,"b":3}'


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-005")
def test_numeric_string_keys_sort_lexicographically() -> None:
    """'1' < '10' < '2' under lex order (NOT numeric)."""
    out = jcs_canonicalize({"10": "ten", "2": "two", "1": "one"})
    assert out == b'{"1":"one","10":"ten","2":"two"}'


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-005")
def test_every_sort_utf16_corpus_vector_matches() -> None:
    """Every sort_utf16 corpus vector encodes to its pinned bytes."""
    corpus = _load_corpus()
    failures: list[str] = []
    for case in corpus["cases"]:
        if case.get("category") != "sort_utf16" or case.get("kind") != "value":
            continue
        actual = jcs_canonicalize(case["input"])
        expected = base64.b64decode(case["expected_canonical_b64"])
        if actual != expected:
            failures.append(
                _format_diff(case["name"], "sort_utf16", expected, actual)
            )
    assert not failures, (
        f"VAL-W17-005: {len(failures)} sort_utf16 failure(s):\n\n"
        + "\n\n".join(failures)
    )


# ---------------------------------------------------------------------------
# VAL-W17-022: per-vector full diff on failure
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-022")
def test_diff_formatter_emits_required_fields() -> None:
    """The _format_diff helper produces a message that includes the
    case name, expected vs actual bytes, hex transcripts, and the
    first diverging-byte index. Asserts the diff is per-vector and
    full (not count-only) per VAL-W17-022."""
    msg = _format_diff(
        case_name="example-case",
        case_category="appendix_b",
        expected_bytes=b'{"a":1}',
        actual_bytes=b'{"a":2}',
    )
    assert "example-case" in msg
    assert "appendix_b" in msg
    assert "expected_bytes" in msg
    assert "actual_bytes" in msg
    assert "expected_hex" in msg
    assert "actual_hex" in msg
    assert "first_diff_idx" in msg
    # The differing byte is the '1' vs '2' character at index 5.
    assert "first_diff_idx = 5" in msg


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-022")
def test_diff_formatter_handles_length_mismatch() -> None:
    """A pure length mismatch (one input is a prefix of the other)
    reports first_diff_idx at the boundary, not -1."""
    msg = _format_diff(
        case_name="length-diff",
        case_category="appendix_b",
        expected_bytes=b'{"a":1}',
        actual_bytes=b'{"a":1',
    )
    assert "first_diff_idx = 6" in msg


# ---------------------------------------------------------------------------
# Generator drift guard -- catches a hand-edit to the corpus
# ---------------------------------------------------------------------------


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-001")
def test_corpus_case_names_unique() -> None:
    corpus = _load_corpus()
    seen: set[str] = set()
    for case in corpus["cases"]:
        name = case["name"]
        assert name not in seen, f"duplicate case name in corpus: {name}"
        seen.add(name)
