"""WS-E UDF-via-CEL corpus guard tests (M3 P3CORPUS).

These guards lock the four primaryFulfills assertions for the
``p3corpus-udf-via-cel-corpus-generator`` feature:

  VAL-CWC-P3CORPUS-001 (engines_fence / corpus_shape):
    A NEW corpus ``relay_udf_via_cel_corpus.json`` exists, SEPARATE from
    ``relay_cel_corpus.json``, and is the ONLY file these runners read. Every
    case carries ``engines == ["wasm"]`` (the structural fence excluding
    cel-js). The validating loader REJECTS any case whose ``engines`` is
    missing or not exactly ``["wasm"]``.

  VAL-CWC-P3CORPUS-002 (cel_js_parseable):
    Every case carries a boolean ``cel_js_parseable`` COMPUTED from the
    documented >=2-key map-literal-with-"type" boundary. This guard
    INDEPENDENTLY recomputes the flag (via the SHARED
    ``compute_cel_js_parseable`` the generator also uses) and asserts it
    matches the stored value for every case.

  VAL-CWC-P3CORPUS-003 (golden determinism + cel-python cross-anchor):
    Each case's stored golden equals a FRESH wasm eval (determinism) AND
    equals the cel-python DIRECT-call result serialized to typed-canonical
    (the cross-anchor that replaces the retired two-engine test_w17_4
    comparison).

  VAL-CWC-P3CORPUS-004 (udf_coverage / allowlist):
    All three Relay UDFs are exercised THROUGH CEL with at least one >=2-key
    map-literal boundary case (cel_js_parseable=false) per UDF, and no case
    references any UDF outside the three-name allowlist.

The corpus is generated by ``scripts/generate-relay-udf-via-cel-corpus.py``
from the BUILT wasm
(``packages/cel-wasm/crate/target/wasm32-unknown-unknown/release/relay_cel_wasm.wasm``
or ``$CEL_WASM``). All tests are tier-1 plumbing.

ASCII-only per CLAUDE.md "ASCII-Safe Source".
"""

from __future__ import annotations

import base64
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any

import pytest

# Repo root: this file lives at relay/tests/conformance/cel/test_*.py
REPO_ROOT = Path(__file__).resolve().parents[3]
CORPUS_PATH = REPO_ROOT / "tests" / "conformance" / "cel" / "relay_udf_via_cel_corpus.json"
GENERATOR_PATH = REPO_ROOT / "scripts" / "generate-relay-udf-via-cel-corpus.py"
LEGACY_CORPUS_PATH = REPO_ROOT / "tests" / "conformance" / "cel" / "relay_cel_corpus.json"

# The 3-name UDF allowlist.
UDF_ALLOWLIST: frozenset[str] = frozenset(
    {"relay.coverage", "relay.tool_arg", "relay.schema_match"}
)

# Make the cel-python direct callables + py_to_typed + JCS encoder importable
# for the cross-anchor, and the wasm loader importable for the determinism
# check.
sys.path.insert(0, str(REPO_ROOT / "packages" / "contracts" / "src"))
sys.path.insert(0, str(REPO_ROOT / "packages" / "cel-wasm" / "python"))


def _load_generator() -> Any:
    """Load the hyphenated generator script as a module (a plain import cannot
    resolve a hyphenated filename)."""
    spec = importlib.util.spec_from_file_location(
        "relay_udf_via_cel_corpus_generator_under_test", GENERATOR_PATH
    )
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules["relay_udf_via_cel_corpus_generator_under_test"] = mod
    spec.loader.exec_module(mod)
    return mod


def _load_corpus() -> dict[str, Any]:
    assert CORPUS_PATH.exists(), (
        f"VAL-CWC-P3CORPUS-001: missing UDF-via-CEL corpus at {CORPUS_PATH}; "
        "regenerate via `uv run python scripts/generate-relay-udf-via-cel-corpus.py`."
    )
    data = json.loads(CORPUS_PATH.read_text(encoding="utf-8"))
    assert isinstance(data, dict), "corpus root must be a JSON object"
    return data


def _cases() -> list[dict[str, Any]]:
    cases = _load_corpus().get("cases")
    assert isinstance(cases, list) and cases, "corpus must carry a non-empty 'cases' list"
    return cases


# ===========================================================================
# VAL-CWC-P3CORPUS-001: engines:["wasm"] fence + separate file + validating loader
# ===========================================================================


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-001")
def test_udf_via_cel_corpus_shape_separate_file() -> None:
    """The NEW corpus exists, is non-empty, and is a SEPARATE file from
    relay_cel_corpus.json (different path; this runner never reads the legacy
    corpus)."""
    assert CORPUS_PATH.exists(), f"missing {CORPUS_PATH}"
    assert CORPUS_PATH != LEGACY_CORPUS_PATH
    assert LEGACY_CORPUS_PATH.exists(), "legacy corpus must still exist (untouched)"
    cases = _cases()
    assert len(cases) > 0


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-001")
def test_udf_via_cel_corpus_engines_fence_every_case() -> None:
    """Every case carries engines == ["wasm"] exactly (structural cel-js fence)."""
    offenders = [
        c.get("label") for c in _cases() if c.get("engines") != ["wasm"]
    ]
    assert offenders == [], (
        "VAL-CWC-P3CORPUS-001: every case MUST carry engines == ['wasm']; "
        f"offenders: {offenders}"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-001")
def test_loader_rejects_missing_engines() -> None:
    """The validating loader REJECTS a case whose 'engines' field is missing."""
    gen = _load_generator()
    bad = {
        "label": "bad_missing_engines",
        "udf": "relay.coverage",
        "input_expression": 'relay.coverage(trace, "x")',
    }
    with pytest.raises((ValueError, AssertionError, KeyError)):
        gen.validate_case_engines(bad)


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-001")
def test_loader_rejects_wrong_engines() -> None:
    """The validating loader REJECTS a case whose 'engines' is not exactly
    ['wasm'] (e.g. includes cel-js, or is reordered/extended)."""
    gen = _load_generator()
    for wrong in (["cel-js"], ["wasm", "cel-js"], [], ["celpy"], "wasm"):
        bad = {
            "label": "bad_wrong_engines",
            "udf": "relay.coverage",
            "input_expression": 'relay.coverage(trace, "x")',
            "engines": wrong,
        }
        with pytest.raises((ValueError, AssertionError)):
            gen.validate_case_engines(bad)


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-001")
def test_loader_accepts_correct_engines() -> None:
    """The validating loader ACCEPTS a case whose 'engines' == ['wasm']."""
    gen = _load_generator()
    good = {
        "label": "ok_engines",
        "udf": "relay.coverage",
        "input_expression": 'relay.coverage(trace, "x")',
        "engines": ["wasm"],
    }
    gen.validate_case_engines(good)  # must not raise


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-001")
def test_every_stored_case_passes_the_loader_validation() -> None:
    """Every on-disk case passes the loader's engines validation."""
    gen = _load_generator()
    for case in _cases():
        gen.validate_case_engines(case)


# ===========================================================================
# VAL-CWC-P3CORPUS-002: cel_js_parseable computed + independently recomputed
# ===========================================================================


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-002")
def test_cel_js_parseable_present_and_boolean() -> None:
    for case in _cases():
        assert isinstance(case.get("cel_js_parseable"), bool), (
            f"VAL-CWC-P3CORPUS-002: case {case.get('label')!r} missing boolean "
            "cel_js_parseable"
        )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-002")
def test_cel_js_parseable_recomputed_matches_stored() -> None:
    """Independently recompute the boundary flag from input_expression (via the
    SHARED classifier the generator also uses) and assert it matches stored."""
    gen = _load_generator()
    mismatches: list[str] = []
    for case in _cases():
        expr = case["input_expression"]
        recomputed = gen.compute_cel_js_parseable(expr)
        stored = case["cel_js_parseable"]
        if recomputed != stored:
            mismatches.append(
                f"{case.get('label')!r}: stored={stored} recomputed={recomputed} "
                f"expr={expr!r}"
            )
    assert mismatches == [], (
        "VAL-CWC-P3CORPUS-002: cel_js_parseable mismatch:\n  " + "\n  ".join(mismatches)
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-002")
def test_cel_js_parseable_classifier_boundary_semantics() -> None:
    """The shared classifier implements the documented boundary precisely:
    a map literal with >=2 keys INCLUDING a "type" key -> False; otherwise True.
    """
    gen = _load_generator()
    f = gen.compute_cel_js_parseable
    # True cases (parseable):
    assert f('relay.coverage(trace, "x")') is True
    assert f('relay.schema_match(42, {"type": "integer"})') is True  # single key
    assert f('relay.tool_arg({"args": {"k": "v"}}, "k")') is True  # no "type" key
    assert f('relay.coverage({"steps": [{"name": "a"}]}, "a")') is True
    # False cases (NOT parseable by cel-js: >=2 keys incl. "type"):
    assert f('relay.schema_match({"a":1}, {"type": "object", "required": ["a"]})') is False
    assert f('relay.tool_arg({"type": "tc", "args": {"k": "v"}}, "k")') is False
    assert f('relay.coverage({"steps": [{"type": "t", "name": "a"}]}, "a")') is False
    # A brace inside a string literal is NOT a map literal (must not false-fire):
    assert f('relay.tool_arg(call, "a{type:b,c:d}")') is True


# ===========================================================================
# VAL-CWC-P3CORPUS-003: goldens from built wasm, deterministic + cross-anchored
# ===========================================================================


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-003")
def test_golden_matches_fresh_wasm_eval() -> None:
    """Each stored golden equals a FRESH wasm eval of the same case through CEL
    (determinism: the built wasm reproduces the recorded golden)."""
    gen = _load_generator()
    cel = gen.RelayCel()
    failures: list[str] = []
    for case in _cases():
        response = gen._wasm_eval(cel, case["input_expression"], case["bindings"])
        fresh_value = response["value"]
        if fresh_value != case["golden_typed"]:
            failures.append(
                f"{case.get('label')!r}: golden={json.dumps(case['golden_typed'], sort_keys=True)} "
                f"fresh={json.dumps(fresh_value, sort_keys=True)}"
            )
        # JCS b64 must also match the fresh recompute.
        from relay_contracts import jcs_canonicalize  # noqa: PLC0415

        fresh_b64 = base64.b64encode(jcs_canonicalize(fresh_value)).decode("ascii")
        if fresh_b64 != case["py_jcs_b64"]:
            failures.append(f"{case.get('label')!r}: py_jcs_b64 drift")
    assert failures == [], (
        "VAL-CWC-P3CORPUS-003: golden != fresh wasm eval:\n  " + "\n  ".join(failures)
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-003")
def test_golden_cross_anchors_cel_python_direct_call() -> None:
    """Each case's golden equals the FIXED cel-python DIRECT-call result
    serialized to typed-canonical (the parity that replaces the retired
    two-engine test_w17_4 comparison)."""
    gen = _load_generator()
    from relay_contracts.wasm_codec import py_to_typed  # noqa: PLC0415

    failures: list[str] = []
    for case in _cases():
        direct = gen._apply_direct(case["udf"], case["direct_args"])
        direct_typed = py_to_typed(direct)
        if direct_typed != case["golden_typed"]:
            failures.append(
                f"{case.get('label')!r}: wasm-golden="
                f"{json.dumps(case['golden_typed'], sort_keys=True)} "
                f"cel-py-direct={json.dumps(direct_typed, sort_keys=True)}"
            )
    assert failures == [], (
        "VAL-CWC-P3CORPUS-003: cross-anchor wasm-via-CEL != cel-python-direct:\n  "
        + "\n  ".join(failures)
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-003")
def test_generator_check_mode_reports_no_drift() -> None:
    """Re-running the generator in --check mode against the on-disk corpus
    reports no drift (the corpus is byte-deterministic vs a fresh run)."""
    gen = _load_generator()
    corpus = gen.build_corpus()
    serialised = json.dumps(corpus, indent=2, sort_keys=True) + "\n"
    on_disk = CORPUS_PATH.read_text(encoding="utf-8")
    assert serialised == on_disk, (
        "VAL-CWC-P3CORPUS-003: corpus drift -- regenerate via "
        "`uv run python scripts/generate-relay-udf-via-cel-corpus.py`"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-003")
def test_generator_aborts_on_cross_anchor_divergence() -> None:
    """A deliberately-wrong direct-call result makes build_case raise the
    cross-anchor divergence (the abort path is real, not vacuous)."""
    gen = _load_generator()
    cel = gen.RelayCel()
    spec = {
        "label": "deliberate_divergence",
        "udf": "relay.coverage",
        # wasm-via-CEL returns true here; direct_args force a FALSE direct
        # result, so the cross-anchor MUST diverge and abort.
        "input_expression": 'relay.coverage({"steps": [{"name": "a"}]}, "a")',
        "bindings_py": {},
        "direct_args": [{"steps": [{"name": "a"}]}, "DELIBERATELY_WRONG"],
    }
    with pytest.raises(gen.CrossAnchorDivergence) as exc:
        gen.build_case(cel, spec)
    assert exc.value.label == "deliberate_divergence"
    assert exc.value.wasm_value != exc.value.direct_value


# ===========================================================================
# VAL-CWC-P3CORPUS-004: all 3 UDFs through CEL, boundary per UDF, allowlist-only
# ===========================================================================


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-004")
def test_udf_coverage_all_three_udfs_present_allowlist_only() -> None:
    """udf_coverage guard (VAL-CWC-P3CORPUS-004): all three allowlist UDFs are
    exercised, and no case references a UDF outside the allowlist."""
    udfs_used = {c["udf"] for c in _cases()}
    assert udfs_used == UDF_ALLOWLIST, (
        "VAL-CWC-P3CORPUS-004: corpus must exercise exactly the 3 allowlist UDFs; "
        f"got {sorted(udfs_used)}"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-004")
def test_cases_drive_through_cel_dotted_form() -> None:
    """Every case drives the UDF THROUGH CEL: the input_expression contains the
    dotted UDF call (not a direct Python callable invocation)."""
    for case in _cases():
        expr = case["input_expression"]
        assert case["udf"] + "(" in expr, (
            f"VAL-CWC-P3CORPUS-004: case {case.get('label')!r} must drive "
            f"{case['udf']} THROUGH CEL (dotted call in input_expression)"
        )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-CWC-P3CORPUS-004")
def test_at_least_one_boundary_case_per_udf() -> None:
    """Each UDF has at least one >=2-key map-literal boundary case that cel-js
    cannot parse (cel_js_parseable == false)."""
    boundary_by_udf: dict[str, int] = {}
    for case in _cases():
        if case["cel_js_parseable"] is False:
            boundary_by_udf[case["udf"]] = boundary_by_udf.get(case["udf"], 0) + 1
    missing = [udf for udf in UDF_ALLOWLIST if boundary_by_udf.get(udf, 0) < 1]
    assert missing == [], (
        "VAL-CWC-P3CORPUS-004: each UDF needs >= 1 cel_js_parseable=false boundary "
        f"case; missing for: {sorted(missing)}"
    )
