"""W17.4 VAL-W17-015: per-UDF case coverage.

Asserts the Relay-CEL Conformance Corpus at
``tests/conformance/cel/relay-udfs/`` contains a subdirectory per
production Relay UDF (relay.coverage, relay.tool_arg,
relay.schema_match), each with >= 5 paired Py/TS test cases that
validate against the shared case schema.

The case files are generated by
``scripts/generate-w17-4-udf-cases.py`` from
``tests/conformance/cel/relay_cel_corpus.json`` (W6.5 corpus).

Tool: conformance-corpus-test (pytest plumbing tier).
ASCII-only per CLAUDE.md.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
RELAY_UDFS_DIR = REPO_ROOT / "tests" / "conformance" / "cel" / "relay-udfs"
CASE_SCHEMA_PATH = RELAY_UDFS_DIR / "case.schema.json"

# The three production UDFs ship in v0.1; contract assertion names them
# explicitly ("at minimum relay.coverage/, relay.tool_arg/,
# relay.schema_match/").
REQUIRED_UDFS: tuple[str, ...] = (
    "relay.coverage",
    "relay.tool_arg",
    "relay.schema_match",
)
MIN_CASES_PER_UDF: int = 5

# Required fields per case file (must match the contract: input CEL
# expression, input bindings, expected output, label).
REQUIRED_CASE_FIELDS: set[str] = {
    "label",
    "udf",
    "args",
    "input_expression",
    "input_bindings",
    "expected_output",
    "py_jcs_b64",
}


def _load_schema() -> dict[str, object]:
    return json.loads(CASE_SCHEMA_PATH.read_text(encoding="utf-8"))


def _validate_case_against_schema(case: dict[str, object], schema: dict[str, object]) -> list[str]:
    """Minimal in-tree JSON-schema validator for the W17.4 case schema.

    Implements the subset the schema actually uses:
      - required fields present
      - additionalProperties == False enforced
      - property type checks (string/object/array)
      - enum constraint on `udf`
      - minItems on `args`
      - minLength on string fields

    Returns a list of human-readable error strings (empty -> valid).
    Implemented in-tree because the workspace does not pin jsonschema.
    """

    errors: list[str] = []
    required = schema.get("required", [])
    if isinstance(required, list):
        for field in required:
            if field not in case:
                errors.append(f"missing required field {field!r}")
    properties = schema.get("properties", {})
    if not isinstance(properties, dict):
        return errors
    additional = schema.get("additionalProperties", True)
    if additional is False:
        extra = set(case.keys()) - set(properties.keys())
        if extra:
            errors.append(f"unknown fields not allowed by schema: {sorted(extra)}")
    for key, value in case.items():
        prop = properties.get(key)
        if not isinstance(prop, dict):
            continue
        ptype = prop.get("type")
        if ptype == "string":
            if not isinstance(value, str):
                errors.append(f"{key}: expected string, got {type(value).__name__}")
                continue
            minlen = prop.get("minLength")
            if isinstance(minlen, int) and len(value) < minlen:
                errors.append(f"{key}: length {len(value)} < minLength {minlen}")
            enum = prop.get("enum")
            if isinstance(enum, list) and value not in enum:
                errors.append(f"{key}: {value!r} not in enum {enum}")
        elif ptype == "object":
            if not isinstance(value, dict):
                errors.append(f"{key}: expected object, got {type(value).__name__}")
        elif ptype == "array":
            if not isinstance(value, list):
                errors.append(f"{key}: expected array, got {type(value).__name__}")
                continue
            minitems = prop.get("minItems")
            if isinstance(minitems, int) and len(value) < minitems:
                errors.append(f"{key}: {len(value)} items < minItems {minitems}")
    return errors


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-015")
def test_relay_udfs_directory_exists() -> None:
    assert RELAY_UDFS_DIR.exists(), (
        f"VAL-W17-015: missing per-UDF corpus directory at {RELAY_UDFS_DIR}; "
        "regenerate via `uv run python scripts/generate-w17-4-udf-cases.py`."
    )
    assert RELAY_UDFS_DIR.is_dir(), f"{RELAY_UDFS_DIR} is not a directory"


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-015")
def test_case_schema_present() -> None:
    assert CASE_SCHEMA_PATH.exists(), (
        f"VAL-W17-015: case.schema.json missing at {CASE_SCHEMA_PATH}; "
        "the per-UDF schema MUST exist so case files can be validated."
    )
    schema = _load_schema()
    assert schema.get("$id", "").endswith("/udf-case.json"), (
        f"VAL-W17-015: case.schema.json missing $id; got {schema.get('$id')!r}"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-015")
def test_every_required_udf_has_subdirectory() -> None:
    missing: list[str] = []
    for udf in REQUIRED_UDFS:
        if not (RELAY_UDFS_DIR / udf).is_dir():
            missing.append(udf)
    assert missing == [], (
        f"VAL-W17-015: missing per-UDF subdirectories: {missing}; "
        f"expected one of {REQUIRED_UDFS}"
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-015")
def test_every_udf_has_minimum_case_count() -> None:
    short: list[str] = []
    for udf in REQUIRED_UDFS:
        udf_dir = RELAY_UDFS_DIR / udf
        cases = sorted(udf_dir.glob("case_*.json"))
        if len(cases) < MIN_CASES_PER_UDF:
            short.append(f"{udf}: {len(cases)} cases (need >= {MIN_CASES_PER_UDF})")
    assert short == [], (
        "VAL-W17-015: per-UDF case-count floor not met:\n  " + "\n  ".join(short)
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-015")
def test_every_case_file_validates_against_schema() -> None:
    schema = _load_schema()
    failures: list[str] = []
    for udf in REQUIRED_UDFS:
        udf_dir = RELAY_UDFS_DIR / udf
        if not udf_dir.is_dir():
            continue
        for case_path in sorted(udf_dir.glob("case_*.json")):
            try:
                case = json.loads(case_path.read_text(encoding="utf-8"))
            except json.JSONDecodeError as exc:
                failures.append(f"{case_path.name}: JSON decode error: {exc}")
                continue
            if not isinstance(case, dict):
                failures.append(f"{case_path.name}: case root must be an object")
                continue
            errors = _validate_case_against_schema(case, schema)
            for err in errors:
                failures.append(f"{udf}/{case_path.name}: {err}")
    assert failures == [], (
        "VAL-W17-015: case-file schema validation errors:\n  "
        + "\n  ".join(failures)
    )


@pytest.mark.plumbing
@pytest.mark.fulfills("VAL-W17-015")
def test_every_case_has_required_fields() -> None:
    """Per the contract: each case MUST consist of input CEL expression,
    input bindings (JSON), expected output (JSON), and a label."""

    failures: list[str] = []
    for udf in REQUIRED_UDFS:
        udf_dir = RELAY_UDFS_DIR / udf
        if not udf_dir.is_dir():
            continue
        for case_path in sorted(udf_dir.glob("case_*.json")):
            case = json.loads(case_path.read_text(encoding="utf-8"))
            missing = REQUIRED_CASE_FIELDS - set(case.keys())
            if missing:
                failures.append(
                    f"{udf}/{case_path.name}: missing fields {sorted(missing)}"
                )
            if case.get("udf") != udf:
                failures.append(
                    f"{udf}/{case_path.name}: udf field {case.get('udf')!r} "
                    f"does not match parent dir"
                )
    assert failures == [], (
        "VAL-W17-015: case-file required-field check failed:\n  "
        + "\n  ".join(failures)
    )
